# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SamplePackage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SamplePackage.proto\x12\x17\x64omain.SamplePackage.v1\"%\n\rSampleMessage\x12\x14\n\x0cSampleString\x18\x01 \x01(\tb\x06proto3')



_SAMPLEMESSAGE = DESCRIPTOR.message_types_by_name['SampleMessage']

@overload
class SampleMessage:
	"""webezyio generated message [domain.SamplePackage.v1.SampleMessage]
	A class respresent a SampleMessage type
	"""
	SampleString = str # type: str

	def __init__(self, SampleString=str):
		pass
SampleMessage = _reflection.GeneratedProtocolMessageType('SampleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEMESSAGE,
  '__module__' : 'SamplePackage_pb2'
  # @@protoc_insertion_point(class_scope:domain.SamplePackage.v1.SampleMessage)
  })
_sym_db.RegisterMessage(SampleMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLEMESSAGE._serialized_start=48
  _SAMPLEMESSAGE._serialized_end=85
# @@protoc_insertion_point(module_scope)
