# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EnumValues.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x45numValues.proto\x1a\x0fWebezyApi.proto2\xbb\x03\n\nEnumValues\x12\x63\n\x0cGetEnumValue\x12(.webezy.WebezyApi.v1.GetEnumValueRequest\x1a).webezy.WebezyApi.v1.GetEnumValueResponse\x12l\n\x0f\x43reateEnumValue\x12+.webezy.WebezyApi.v1.CreateEnumValueRequest\x1a,.webezy.WebezyApi.v1.CreateEnumValueResponse\x12l\n\x0fUpdateEnumValue\x12+.webezy.WebezyApi.v1.UpdateEnumValueRequest\x1a,.webezy.WebezyApi.v1.UpdateEnumValueResponse\x12l\n\x0f\x44\x65leteEnumValue\x12+.webezy.WebezyApi.v1.DeleteEnumValueRequest\x1a,.webezy.WebezyApi.v1.DeleteEnumValueResponseb\x06proto3')



_ENUMVALUES = DESCRIPTOR.services_by_name['EnumValues']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENUMVALUES._serialized_start=38
  _ENUMVALUES._serialized_end=481
# @@protoc_insertion_point(module_scope)
