# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Enums.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x45nums.proto\x1a\x0fWebezyApi.proto2\xfa\x02\n\x05\x45nums\x12T\n\x07GetEnum\x12#.webezy.WebezyApi.v1.GetEnumRequest\x1a$.webezy.WebezyApi.v1.GetEnumResponse\x12]\n\nCreateEnum\x12&.webezy.WebezyApi.v1.CreateEnumRequest\x1a\'.webezy.WebezyApi.v1.CreateEnumResponse\x12]\n\nUpdateEnum\x12&.webezy.WebezyApi.v1.UpdateEnumRequest\x1a\'.webezy.WebezyApi.v1.UpdateEnumResponse\x12]\n\nDeleteEnum\x12&.webezy.WebezyApi.v1.DeleteEnumRequest\x1a\'.webezy.WebezyApi.v1.DeleteEnumResponseb\x06proto3')



_ENUMS = DESCRIPTOR.services_by_name['Enums']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENUMS._serialized_start=33
  _ENUMS._serialized_end=411
# @@protoc_insertion_point(module_scope)
