# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyApi_pb2 as WebezyApi__pb2


class EnumsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEnum = channel.unary_unary(
                '/Enums/GetEnum',
                request_serializer=WebezyApi__pb2.GetEnumRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetEnumResponse.FromString,
                )
        self.CreateEnum = channel.unary_unary(
                '/Enums/CreateEnum',
                request_serializer=WebezyApi__pb2.CreateEnumRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateEnumResponse.FromString,
                )
        self.UpdateEnum = channel.unary_unary(
                '/Enums/UpdateEnum',
                request_serializer=WebezyApi__pb2.UpdateEnumRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.UpdateEnumResponse.FromString,
                )
        self.DeleteEnum = channel.unary_unary(
                '/Enums/DeleteEnum',
                request_serializer=WebezyApi__pb2.DeleteEnumRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.DeleteEnumResponse.FromString,
                )


class EnumsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEnum(self, request, context):
        """[webezyio] - Get enum request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEnum(self, request, context):
        """[webezyio] - Create a new enum object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEnum(self, request, context):
        """[webezyio] - Update a enum object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEnum(self, request, context):
        """[webezyio] - Delete an enum object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnumsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnum,
                    request_deserializer=WebezyApi__pb2.GetEnumRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetEnumResponse.SerializeToString,
            ),
            'CreateEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEnum,
                    request_deserializer=WebezyApi__pb2.CreateEnumRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateEnumResponse.SerializeToString,
            ),
            'UpdateEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEnum,
                    request_deserializer=WebezyApi__pb2.UpdateEnumRequest.FromString,
                    response_serializer=WebezyApi__pb2.UpdateEnumResponse.SerializeToString,
            ),
            'DeleteEnum': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEnum,
                    request_deserializer=WebezyApi__pb2.DeleteEnumRequest.FromString,
                    response_serializer=WebezyApi__pb2.DeleteEnumResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Enums', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Enums(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Enums/GetEnum',
            WebezyApi__pb2.GetEnumRequest.SerializeToString,
            WebezyApi__pb2.GetEnumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Enums/CreateEnum',
            WebezyApi__pb2.CreateEnumRequest.SerializeToString,
            WebezyApi__pb2.CreateEnumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Enums/UpdateEnum',
            WebezyApi__pb2.UpdateEnumRequest.SerializeToString,
            WebezyApi__pb2.UpdateEnumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteEnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Enums/DeleteEnum',
            WebezyApi__pb2.DeleteEnumRequest.SerializeToString,
            WebezyApi__pb2.DeleteEnumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
