# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Fields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x46ields.proto\x1a\x0fWebezyApi.proto2\x84\x03\n\x06\x46ields\x12]\n\x0b\x43reateField\x12\'.webezy.WebezyApi.v1.CreateFieldRequest\x1a%.webezy.WebezyApi.v1.GetFieldResponse\x12W\n\x08GetField\x12$.webezy.WebezyApi.v1.GetFieldRequest\x1a%.webezy.WebezyApi.v1.GetFieldResponse\x12`\n\x0bUpdateField\x12\'.webezy.WebezyApi.v1.UpdateFieldRequest\x1a(.webezy.WebezyApi.v1.UpdateFieldResponse\x12`\n\x0b\x44\x65leteField\x12\'.webezy.WebezyApi.v1.DeleteFieldRequest\x1a(.webezy.WebezyApi.v1.DeleteFieldResponseb\x06proto3')



_FIELDS = DESCRIPTOR.services_by_name['Fields']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIELDS._serialized_start=34
  _FIELDS._serialized_end=422
# @@protoc_insertion_point(module_scope)
