# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eMessages.proto\x1a\x0fWebezyApi.proto2\xa1\x03\n\x08Messages\x12\x66\n\rCreateMessage\x12).webezy.WebezyApi.v1.CreateMessageRequest\x1a*.webezy.WebezyApi.v1.CreateMessageResponse\x12\x66\n\rUpdateMessage\x12).webezy.WebezyApi.v1.UpdateMessageRequest\x1a*.webezy.WebezyApi.v1.UpdateMessageResponse\x12\x66\n\rDeleteMessage\x12).webezy.WebezyApi.v1.DeleteMessageRequest\x1a*.webezy.WebezyApi.v1.DeleteMessageResponse\x12]\n\nGetMessage\x12&.webezy.WebezyApi.v1.GetMessageRequest\x1a\'.webezy.WebezyApi.v1.GetMessageResponseb\x06proto3')



_MESSAGES = DESCRIPTOR.services_by_name['Messages']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGES._serialized_start=36
  _MESSAGES._serialized_end=453
# @@protoc_insertion_point(module_scope)
