# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyApi_pb2 as WebezyApi__pb2


class MethodsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMethod = channel.unary_unary(
                '/Methods/CreateMethod',
                request_serializer=WebezyApi__pb2.CreateMethodRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateMethodResponse.FromString,
                )
        self.GetMethod = channel.unary_unary(
                '/Methods/GetMethod',
                request_serializer=WebezyApi__pb2.GetMethodRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetMethodResponse.FromString,
                )
        self.UpdateMethod = channel.unary_unary(
                '/Methods/UpdateMethod',
                request_serializer=WebezyApi__pb2.UpdateMethodRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.UpdateMethodResponse.FromString,
                )
        self.DeleteMethod = channel.unary_unary(
                '/Methods/DeleteMethod',
                request_serializer=WebezyApi__pb2.DeleteMethodRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.DeleteMethodResponse.FromString,
                )


class MethodsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMethod(self, request, context):
        """[webezyio] - Create a new method (RPC) on a project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMethod(self, request, context):
        """[webezyio] - Get a method (RPC) description on specified project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMethod(self, request, context):
        """[webezyio] - Update a method (RPC) on specified project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMethod(self, request, context):
        """[webezyio] - Delete a method (RPC) from a project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MethodsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMethod,
                    request_deserializer=WebezyApi__pb2.CreateMethodRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateMethodResponse.SerializeToString,
            ),
            'GetMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMethod,
                    request_deserializer=WebezyApi__pb2.GetMethodRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetMethodResponse.SerializeToString,
            ),
            'UpdateMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMethod,
                    request_deserializer=WebezyApi__pb2.UpdateMethodRequest.FromString,
                    response_serializer=WebezyApi__pb2.UpdateMethodResponse.SerializeToString,
            ),
            'DeleteMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMethod,
                    request_deserializer=WebezyApi__pb2.DeleteMethodRequest.FromString,
                    response_serializer=WebezyApi__pb2.DeleteMethodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Methods', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Methods(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Methods/CreateMethod',
            WebezyApi__pb2.CreateMethodRequest.SerializeToString,
            WebezyApi__pb2.CreateMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Methods/GetMethod',
            WebezyApi__pb2.GetMethodRequest.SerializeToString,
            WebezyApi__pb2.GetMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Methods/UpdateMethod',
            WebezyApi__pb2.UpdateMethodRequest.SerializeToString,
            WebezyApi__pb2.UpdateMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Methods/DeleteMethod',
            WebezyApi__pb2.DeleteMethodRequest.SerializeToString,
            WebezyApi__pb2.DeleteMethodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
