# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Methods.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMethods.proto\x1a\x0fWebezyApi.proto2\x94\x03\n\x07Methods\x12\x63\n\x0c\x43reateMethod\x12(.webezy.WebezyApi.v1.CreateMethodRequest\x1a).webezy.WebezyApi.v1.CreateMethodResponse\x12Z\n\tGetMethod\x12%.webezy.WebezyApi.v1.GetMethodRequest\x1a&.webezy.WebezyApi.v1.GetMethodResponse\x12\x63\n\x0cUpdateMethod\x12(.webezy.WebezyApi.v1.UpdateMethodRequest\x1a).webezy.WebezyApi.v1.UpdateMethodResponse\x12\x63\n\x0c\x44\x65leteMethod\x12(.webezy.WebezyApi.v1.DeleteMethodRequest\x1a).webezy.WebezyApi.v1.DeleteMethodResponseb\x06proto3')



_METHODS = DESCRIPTOR.services_by_name['Methods']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METHODS._serialized_start=35
  _METHODS._serialized_end=439
# @@protoc_insertion_point(module_scope)
