# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Packages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePackages.proto\x1a\x0fWebezyApi.proto2\x88\x04\n\x08Packages\x12]\n\nGetPackage\x12&.webezy.WebezyApi.v1.GetPackageRequest\x1a\'.webezy.WebezyApi.v1.GetPackageResponse\x12\x66\n\rCreatePackage\x12).webezy.WebezyApi.v1.CreatePackageRequest\x1a*.webezy.WebezyApi.v1.CreatePackageResponse\x12\x66\n\rUpdatePackage\x12).webezy.WebezyApi.v1.UpdatePackageRequest\x1a*.webezy.WebezyApi.v1.UpdatePackageResponse\x12\x66\n\rDeletePackage\x12).webezy.WebezyApi.v1.DeletePackageRequest\x1a*.webezy.WebezyApi.v1.DeletePackageResponse\x12\x65\n\x0cListPackages\x12(.webezy.WebezyApi.v1.ListPackagesRequest\x1a).webezy.WebezyApi.v1.ListPackagesResponse0\x01\x62\x06proto3')



_PACKAGES = DESCRIPTOR.services_by_name['Packages']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PACKAGES._serialized_start=36
  _PACKAGES._serialized_end=556
# @@protoc_insertion_point(module_scope)
