# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Platform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePlatform.proto\x1a\x0fWebezyApi.proto2\xc6\x06\n\x08Platform\x12T\n\x07GetUser\x12#.webezy.WebezyApi.v1.GetUserRequest\x1a$.webezy.WebezyApi.v1.GetUserResponse\x12]\n\nCreateUser\x12&.webezy.WebezyApi.v1.CreateUserRequest\x1a\'.webezy.WebezyApi.v1.CreateUserResponse\x12l\n\x0fGetOrganization\x12+.webezy.WebezyApi.v1.GetOrganizationRequest\x1a,.webezy.WebezyApi.v1.GetOrganizationResponse\x12u\n\x12\x43reateOrganization\x12..webezy.WebezyApi.v1.CreateOrganizationRequest\x1a/.webezy.WebezyApi.v1.CreateOrganizationResponse\x12]\n\nGetProject\x12&.webezy.WebezyApi.v1.GetProjectRequest\x1a\'.webezy.WebezyApi.v1.GetProjectResponse\x12\x66\n\rCreateProject\x12).webezy.WebezyApi.v1.CreateProjectRequest\x1a*.webezy.WebezyApi.v1.CreateProjectResponse\x12\x65\n\x0cListProjects\x12(.webezy.WebezyApi.v1.ListProjectsRequest\x1a).webezy.WebezyApi.v1.ListProjectsResponse0\x01\x12r\n\x11ListOrganizations\x12-.webezy.WebezyApi.v1.ListOrganizationsRequest\x1a,.webezy.WebezyApi.v1.GetOrganizationResponse0\x01\x62\x06proto3')



_PLATFORM = DESCRIPTOR.services_by_name['Platform']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLATFORM._serialized_start=36
  _PLATFORM._serialized_end=874
# @@protoc_insertion_point(module_scope)
