# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyApi_pb2 as WebezyApi__pb2


class PlatformStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/Platform/GetUser',
                request_serializer=WebezyApi__pb2.GetUserRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetUserResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/Platform/CreateUser',
                request_serializer=WebezyApi__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateUserResponse.FromString,
                )
        self.GetOrganization = channel.unary_unary(
                '/Platform/GetOrganization',
                request_serializer=WebezyApi__pb2.GetOrganizationRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetOrganizationResponse.FromString,
                )
        self.CreateOrganization = channel.unary_unary(
                '/Platform/CreateOrganization',
                request_serializer=WebezyApi__pb2.CreateOrganizationRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateOrganizationResponse.FromString,
                )
        self.GetProject = channel.unary_unary(
                '/Platform/GetProject',
                request_serializer=WebezyApi__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetProjectResponse.FromString,
                )
        self.CreateProject = channel.unary_unary(
                '/Platform/CreateProject',
                request_serializer=WebezyApi__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateProjectResponse.FromString,
                )
        self.ListProjects = channel.unary_stream(
                '/Platform/ListProjects',
                request_serializer=WebezyApi__pb2.ListProjectsRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.ListProjectsResponse.FromString,
                )
        self.ListOrganizations = channel.unary_stream(
                '/Platform/ListOrganizations',
                request_serializer=WebezyApi__pb2.ListOrganizationsRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetOrganizationResponse.FromString,
                )


class PlatformServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """[webezyio] - Get a user info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """[webezyio] - Create a new user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrganization(self, request, context):
        """[webezyio] - Get organization info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrganization(self, request, context):
        """[webezyio] - Create organization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """[webezyio] - Get a project info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """[webezyio] - Create a new project under organization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjects(self, request, context):
        """[webezyio] - List all organization projects
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOrganizations(self, request, context):
        """[webezyio] - List organizations under user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=WebezyApi__pb2.GetUserRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetUserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=WebezyApi__pb2.CreateUserRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrganization,
                    request_deserializer=WebezyApi__pb2.GetOrganizationRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetOrganizationResponse.SerializeToString,
            ),
            'CreateOrganization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrganization,
                    request_deserializer=WebezyApi__pb2.CreateOrganizationRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateOrganizationResponse.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=WebezyApi__pb2.GetProjectRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetProjectResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=WebezyApi__pb2.CreateProjectRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateProjectResponse.SerializeToString,
            ),
            'ListProjects': grpc.unary_stream_rpc_method_handler(
                    servicer.ListProjects,
                    request_deserializer=WebezyApi__pb2.ListProjectsRequest.FromString,
                    response_serializer=WebezyApi__pb2.ListProjectsResponse.SerializeToString,
            ),
            'ListOrganizations': grpc.unary_stream_rpc_method_handler(
                    servicer.ListOrganizations,
                    request_deserializer=WebezyApi__pb2.ListOrganizationsRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetOrganizationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Platform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Platform(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/GetUser',
            WebezyApi__pb2.GetUserRequest.SerializeToString,
            WebezyApi__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/CreateUser',
            WebezyApi__pb2.CreateUserRequest.SerializeToString,
            WebezyApi__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/GetOrganization',
            WebezyApi__pb2.GetOrganizationRequest.SerializeToString,
            WebezyApi__pb2.GetOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateOrganization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/CreateOrganization',
            WebezyApi__pb2.CreateOrganizationRequest.SerializeToString,
            WebezyApi__pb2.CreateOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/GetProject',
            WebezyApi__pb2.GetProjectRequest.SerializeToString,
            WebezyApi__pb2.GetProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Platform/CreateProject',
            WebezyApi__pb2.CreateProjectRequest.SerializeToString,
            WebezyApi__pb2.CreateProjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Platform/ListProjects',
            WebezyApi__pb2.ListProjectsRequest.SerializeToString,
            WebezyApi__pb2.ListProjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListOrganizations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Platform/ListOrganizations',
            WebezyApi__pb2.ListOrganizationsRequest.SerializeToString,
            WebezyApi__pb2.GetOrganizationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
