# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Repos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRepos.proto\x1a\x0fWebezyApi.proto2\x98\x02\n\x05Repos\x12T\n\x07GetRepo\x12#.webezy.WebezyApi.v1.GetRepoRequest\x1a$.webezy.WebezyApi.v1.GetRepoResponse\x12]\n\nCreateRepo\x12&.webezy.WebezyApi.v1.CreateRepoRequest\x1a\'.webezy.WebezyApi.v1.CreateRepoResponse\x12Z\n\tListRepos\x12%.webezy.WebezyApi.v1.ListReposRequest\x1a&.webezy.WebezyApi.v1.ListReposResponseb\x06proto3')



_REPOS = DESCRIPTOR.services_by_name['Repos']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPOS._serialized_start=33
  _REPOS._serialized_end=313
# @@protoc_insertion_point(module_scope)
