# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyApi_pb2 as WebezyApi__pb2


class ReposStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRepo = channel.unary_unary(
                '/Repos/GetRepo',
                request_serializer=WebezyApi__pb2.GetRepoRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetRepoResponse.FromString,
                )
        self.CreateRepo = channel.unary_unary(
                '/Repos/CreateRepo',
                request_serializer=WebezyApi__pb2.CreateRepoRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateRepoResponse.FromString,
                )
        self.ListRepos = channel.unary_unary(
                '/Repos/ListRepos',
                request_serializer=WebezyApi__pb2.ListReposRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.ListReposResponse.FromString,
                )


class ReposServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRepo(self, request, context):
        """[webezyio] - Get a specified repo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRepo(self, request, context):
        """[webezyio] - Creeate a new repo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRepos(self, request, context):
        """[webezyio] - List repos under specified organization
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReposServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRepo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepo,
                    request_deserializer=WebezyApi__pb2.GetRepoRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetRepoResponse.SerializeToString,
            ),
            'CreateRepo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRepo,
                    request_deserializer=WebezyApi__pb2.CreateRepoRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateRepoResponse.SerializeToString,
            ),
            'ListRepos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRepos,
                    request_deserializer=WebezyApi__pb2.ListReposRequest.FromString,
                    response_serializer=WebezyApi__pb2.ListReposResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Repos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Repos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRepo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Repos/GetRepo',
            WebezyApi__pb2.GetRepoRequest.SerializeToString,
            WebezyApi__pb2.GetRepoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateRepo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Repos/CreateRepo',
            WebezyApi__pb2.CreateRepoRequest.SerializeToString,
            WebezyApi__pb2.CreateRepoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRepos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Repos/ListRepos',
            WebezyApi__pb2.ListReposRequest.SerializeToString,
            WebezyApi__pb2.ListReposResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
