# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyApi_pb2 as WebezyApi__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eServices.proto\x1a\x0fWebezyApi.proto2\x88\x04\n\x08Services\x12]\n\nGetService\x12&.webezy.WebezyApi.v1.GetServiceRequest\x1a\'.webezy.WebezyApi.v1.GetServiceResponse\x12\x66\n\rCreateService\x12).webezy.WebezyApi.v1.CreateServiceRequest\x1a*.webezy.WebezyApi.v1.CreateServiceResponse\x12\x66\n\rUpdateService\x12).webezy.WebezyApi.v1.UpdateServiceRequest\x1a*.webezy.WebezyApi.v1.UpdateServiceResponse\x12\x66\n\rDeleteService\x12).webezy.WebezyApi.v1.DeleteServiceRequest\x1a*.webezy.WebezyApi.v1.DeleteServiceResponse\x12\x65\n\x0cListServices\x12(.webezy.WebezyApi.v1.ListServicesRequest\x1a).webezy.WebezyApi.v1.ListServicesResponse0\x01\x62\x06proto3')



_SERVICES = DESCRIPTOR.services_by_name['Services']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICES._serialized_start=36
  _SERVICES._serialized_end=556
# @@protoc_insertion_point(module_scope)
