# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyApi_pb2 as WebezyApi__pb2


class ServicesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetService = channel.unary_unary(
                '/Services/GetService',
                request_serializer=WebezyApi__pb2.GetServiceRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.GetServiceResponse.FromString,
                )
        self.CreateService = channel.unary_unary(
                '/Services/CreateService',
                request_serializer=WebezyApi__pb2.CreateServiceRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.CreateServiceResponse.FromString,
                )
        self.UpdateService = channel.unary_unary(
                '/Services/UpdateService',
                request_serializer=WebezyApi__pb2.UpdateServiceRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.UpdateServiceResponse.FromString,
                )
        self.DeleteService = channel.unary_unary(
                '/Services/DeleteService',
                request_serializer=WebezyApi__pb2.DeleteServiceRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.DeleteServiceResponse.FromString,
                )
        self.ListServices = channel.unary_stream(
                '/Services/ListServices',
                request_serializer=WebezyApi__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=WebezyApi__pb2.ListServicesResponse.FromString,
                )


class ServicesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetService(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateService(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateService(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteService(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """[webezyio] - List all services under project
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetService': grpc.unary_unary_rpc_method_handler(
                    servicer.GetService,
                    request_deserializer=WebezyApi__pb2.GetServiceRequest.FromString,
                    response_serializer=WebezyApi__pb2.GetServiceResponse.SerializeToString,
            ),
            'CreateService': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateService,
                    request_deserializer=WebezyApi__pb2.CreateServiceRequest.FromString,
                    response_serializer=WebezyApi__pb2.CreateServiceResponse.SerializeToString,
            ),
            'UpdateService': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateService,
                    request_deserializer=WebezyApi__pb2.UpdateServiceRequest.FromString,
                    response_serializer=WebezyApi__pb2.UpdateServiceResponse.SerializeToString,
            ),
            'DeleteService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteService,
                    request_deserializer=WebezyApi__pb2.DeleteServiceRequest.FromString,
                    response_serializer=WebezyApi__pb2.DeleteServiceResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_stream_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=WebezyApi__pb2.ListServicesRequest.FromString,
                    response_serializer=WebezyApi__pb2.ListServicesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Services', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Services(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/GetService',
            WebezyApi__pb2.GetServiceRequest.SerializeToString,
            WebezyApi__pb2.GetServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/CreateService',
            WebezyApi__pb2.CreateServiceRequest.SerializeToString,
            WebezyApi__pb2.CreateServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/UpdateService',
            WebezyApi__pb2.UpdateServiceRequest.SerializeToString,
            WebezyApi__pb2.UpdateServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Services/DeleteService',
            WebezyApi__pb2.DeleteServiceRequest.SerializeToString,
            WebezyApi__pb2.DeleteServiceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Services/ListServices',
            WebezyApi__pb2.ListServicesRequest.SerializeToString,
            WebezyApi__pb2.ListServicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
