# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyPlatform.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyCore_pb2 as WebezyCore__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WebezyPlatform.proto\x12\x18webezy.WebezyPlatform.v1\x1a\x10WebezyCore.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x19google/protobuf/any.proto\"\xb1\x01\n\nWebezyUser\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x16\n\x0e\x65mail_verified\x18\x02 \x01(\x08\x12\x13\n\x0b\x66\x61mily_name\x18\x03 \x01(\t\x12\x12\n\ngiven_name\x18\x04 \x01(\t\x12\x0e\n\x06locale\x18\x05 \x01(\t\x12\x10\n\x08nickname\x18\x06 \x01(\t\x12\x0f\n\x07picture\x18\x07 \x01(\t\x12\x0f\n\x07user_id\x18\x08 \x01(\t\x12\x0f\n\x07orgsIds\x18\t \x03(\t\"\xba\x01\n\x12WebezyOrganization\x12\x0e\n\x06org_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x05users\x18\x03 \x03(\x0b\x32$.webezy.WebezyPlatform.v1.WebezyUser\x12\n\n\x02id\x18\x04 \x01(\t\x12\x35\n\x08projects\x18\x05 \x03(\x0b\x32#.webezy.WebezyCore.v1.WebezyProject\x12\x0e\n\x06\x64omain\x18\x06 \x01(\tb\x06proto3')



_WEBEZYUSER = DESCRIPTOR.message_types_by_name['WebezyUser']
_WEBEZYORGANIZATION = DESCRIPTOR.message_types_by_name['WebezyOrganization']
WebezyUser = _reflection.GeneratedProtocolMessageType('WebezyUser', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYUSER,
  '__module__' : 'WebezyPlatform_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyPlatform.v1.WebezyUser)
  })
_sym_db.RegisterMessage(WebezyUser)

WebezyOrganization = _reflection.GeneratedProtocolMessageType('WebezyOrganization', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYORGANIZATION,
  '__module__' : 'WebezyPlatform_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyPlatform.v1.WebezyOrganization)
  })
_sym_db.RegisterMessage(WebezyOrganization)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBEZYUSER._serialized_start=126
  _WEBEZYUSER._serialized_end=303
  _WEBEZYORGANIZATION._serialized_start=306
  _WEBEZYORGANIZATION._serialized_end=492
# @@protoc_insertion_point(module_scope)
