# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyAnalytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15WebezyAnalytics.proto\x12\x19webezy.WebezyAnalytics.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"n\n\x08\x43LIEvent\x12\x0f\n\x07version\x18\x01 \x01(\t\x12&\n\x02ts\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x61rgs\x18\x03 \x03(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\n\n\x02os\x18\x05 \x01(\tb\x06proto3')



_CLIEVENT = DESCRIPTOR.message_types_by_name['CLIEvent']

@overload
class CLIEvent(_message.Message):
	"""webezyio generated message [webezy.WebezyAnalytics.v1.CLIEvent]
	A class respresent a CLIEvent type
	This is an CLI analytic event sourced from webezyio CLI
		"""
	version = str # type: str
	ts = google_dot_protobuf_dot_timestamp__pb2.Timestamp # type: google_dot_protobuf_dot_timestamp__pb2.Timestamp
	args = List[str] # type: List[str]
	user_id = str # type: str
	os = str # type: str

	def __init__(self, version=str, ts=google_dot_protobuf_dot_timestamp__pb2.Timestamp, args=List[str], user_id=str, os=str):
		"""
		Attributes:
		----------
		version : str
			The webezyi CLI version
		ts : google_dot_protobuf_dot_timestamp__pb2.Timestamp
			The event trigger timestamp
		args : List[str]
			The arguments passed from user to CLI
		user_id : str
			The user id
		os : str
			The operating system on which the CLI has been ran
		"""
		pass
CLIEvent = _reflection.GeneratedProtocolMessageType('CLIEvent', (_message.Message,), {
  'DESCRIPTOR' : _CLIEVENT,
  '__module__' : 'WebezyAnalytics_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyAnalytics.v1.CLIEvent)
  })
_sym_db.RegisterMessage(CLIEvent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIEVENT._serialized_start=85
  _CLIEVENT._serialized_end=195
# @@protoc_insertion_point(module_scope)
