# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyRepos.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyJson_pb2 as WebezyJson__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11WebezyRepos.proto\x12\x15webezy.WebezyRepos.v1\x1a\x10WebezyJson.proto\x1a\x1cgoogle/protobuf/struct.proto\")\n\x08\x43odeFile\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x03(\x0c\"\x84\x01\n\x10WebezyRepository\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12.\n\x05\x66iles\x18\x02 \x03(\x0b\x32\x1f.webezy.WebezyRepos.v1.CodeFile\x12\x33\n\tresources\x18\x03 \x01(\x0b\x32 .webezy.WebezyJson.v1.WebezyJsonb\x06proto3')



_CODEFILE = DESCRIPTOR.message_types_by_name['CodeFile']
_WEBEZYREPOSITORY = DESCRIPTOR.message_types_by_name['WebezyRepository']
CodeFile = _reflection.GeneratedProtocolMessageType('CodeFile', (_message.Message,), {
  'DESCRIPTOR' : _CODEFILE,
  '__module__' : 'WebezyRepos_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyRepos.v1.CodeFile)
  })
_sym_db.RegisterMessage(CodeFile)

WebezyRepository = _reflection.GeneratedProtocolMessageType('WebezyRepository', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYREPOSITORY,
  '__module__' : 'WebezyRepos_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyRepos.v1.WebezyRepository)
  })
_sym_db.RegisterMessage(WebezyRepository)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODEFILE._serialized_start=92
  _CODEFILE._serialized_end=133
  _WEBEZYREPOSITORY._serialized_start=136
  _WEBEZYREPOSITORY._serialized_end=268
# @@protoc_insertion_point(module_scope)
