# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyPrometheus_pb2 as WebezyPrometheus__pb2
from . import WebezyProxy_pb2 as WebezyProxy__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import WebezyTemplate_pb2 as WebezyTemplate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12WebezyConfig.proto\x12\x16webezy.WebezyConfig.v1\x1a\x16WebezyPrometheus.proto\x1a\x11WebezyProxy.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14WebezyTemplate.proto\"\x1a\n\nWebezyDocs\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\"Q\n\rWebezyMonitor\x12@\n\nprometheus\x18\x01 \x01(\x0b\x32,.webezy.WebezyPrometheus.v1.PrometheusConfig\"\x98\x04\n\x0cWebezyConfig\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12:\n\ndeployment\x18\x03 \x01(\x0e\x32&.webezy.WebezyConfig.v1.DeploymentType\x12\x31\n\x05proxy\x18\x04 \x01(\x0b\x32\".webezy.WebezyProxy.v1.ProxyConfig\x12\x30\n\x04\x64ocs\x18\x05 \x01(\x0b\x32\".webezy.WebezyConfig.v1.WebezyDocs\x12:\n\x08template\x18\x06 \x01(\x0b\x32(.webezy.WebezyTemplate.v1.TemplateConfig\x12\x36\n\x07monitor\x18\x07 \x01(\x0b\x32%.webezy.WebezyConfig.v1.WebezyMonitor\x12\x11\n\tanalytics\x18\x08 \x01(\x08\x12\r\n\x05token\x18\t \x01(\t\x12\x11\n\tfirst_run\x18\n \x01(\x08\x12\x1a\n\x12webezyio_templates\x18\x0b \x03(\t\x12\x44\n\x08\x66\x65\x61tures\x18\x0c \x03(\x0b\x32\x32.webezy.WebezyConfig.v1.WebezyConfig.FeaturesEntry\x12\x0f\n\x07plugins\x18\r \x03(\t\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01*C\n\x0e\x44\x65ploymentType\x12\x1a\n\x16UNKNOWN_DEPLOYMENTTYPE\x10\x00\x12\t\n\x05LOCAL\x10\x01\x12\n\n\x06\x44OCKER\x10\x02\x62\x06proto3')

_DEPLOYMENTTYPE = DESCRIPTOR.enum_types_by_name['DeploymentType']
DeploymentType = enum_type_wrapper.EnumTypeWrapper(_DEPLOYMENTTYPE)
UNKNOWN_DEPLOYMENTTYPE = 0
LOCAL = 1
DOCKER = 2


_WEBEZYDOCS = DESCRIPTOR.message_types_by_name['WebezyDocs']
_WEBEZYMONITOR = DESCRIPTOR.message_types_by_name['WebezyMonitor']
_WEBEZYCONFIG = DESCRIPTOR.message_types_by_name['WebezyConfig']
_WEBEZYCONFIG_FEATURESENTRY = _WEBEZYCONFIG.nested_types_by_name['FeaturesEntry']
WebezyDocs = _reflection.GeneratedProtocolMessageType('WebezyDocs', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYDOCS,
  '__module__' : 'WebezyConfig_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.WebezyDocs)
  })
_sym_db.RegisterMessage(WebezyDocs)

WebezyMonitor = _reflection.GeneratedProtocolMessageType('WebezyMonitor', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYMONITOR,
  '__module__' : 'WebezyConfig_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.WebezyMonitor)
  })
_sym_db.RegisterMessage(WebezyMonitor)

WebezyConfig = _reflection.GeneratedProtocolMessageType('WebezyConfig', (_message.Message,), {

  'FeaturesEntry' : _reflection.GeneratedProtocolMessageType('FeaturesEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEBEZYCONFIG_FEATURESENTRY,
    '__module__' : 'WebezyConfig_pb2'
    # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.WebezyConfig.FeaturesEntry)
    })
  ,
  'DESCRIPTOR' : _WEBEZYCONFIG,
  '__module__' : 'WebezyConfig_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.WebezyConfig)
  })
_sym_db.RegisterMessage(WebezyConfig)
_sym_db.RegisterMessage(WebezyConfig.FeaturesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBEZYCONFIG_FEATURESENTRY._options = None
  _WEBEZYCONFIG_FEATURESENTRY._serialized_options = b'8\001'
  _DEPLOYMENTTYPE._serialized_start=791
  _DEPLOYMENTTYPE._serialized_end=858
  _WEBEZYDOCS._serialized_start=141
  _WEBEZYDOCS._serialized_end=167
  _WEBEZYMONITOR._serialized_start=169
  _WEBEZYMONITOR._serialized_end=250
  _WEBEZYCONFIG._serialized_start=253
  _WEBEZYCONFIG._serialized_end=789
  _WEBEZYCONFIG_FEATURESENTRY._serialized_start=742
  _WEBEZYCONFIG_FEATURESENTRY._serialized_end=789
# @@protoc_insertion_point(module_scope)
