# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyConfig.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyPrometheus_pb2 as WebezyPrometheus__pb2
from . import WebezyProxy_pb2 as WebezyProxy__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import WebezyTemplate_pb2 as WebezyTemplate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12WebezyConfig.proto\x12\x16webezy.WebezyConfig.v1\x1a\x16WebezyPrometheus.proto\x1a\x11WebezyProxy.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14WebezyTemplate.proto\"\xf2\x02\n\x06\x43onfig\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12:\n\ndeployment\x18\x03 \x01(\x0e\x32&.webezy.WebezyConfig.v1.DeploymentType\x12,\n\x05proxy\x18\x04 \x01(\x0b\x32\x1d.webezy.WebezyProxy.v1.Config\x12%\n\x04\x64ocs\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x32\n\x08template\x18\x06 \x01(\x0b\x32 .webezy.WebezyTemplate.v1.Config\x12\x36\n\x07monitor\x18\x07 \x01(\x0b\x32%.webezy.WebezyConfig.v1.WebezyMonitor\x12\x11\n\tanalytics\x18\x08 \x01(\x08\x12\r\n\x05token\x18\t \x01(\t\x12\x11\n\tfirst_run\x18\n \x01(\x08\x12\x1a\n\x12webezyio_templates\x18\x0b \x03(\t\"G\n\rWebezyMonitor\x12\x36\n\nprometheus\x18\x01 \x01(\x0b\x32\".webezy.WebezyPrometheus.v1.Config*C\n\x0e\x44\x65ploymentType\x12\x1a\n\x16UNKNOWN_DEPLOYMENTTYPE\x10\x00\x12\t\n\x05LOCAL\x10\x01\x12\n\n\x06\x44OCKER\x10\x02\x62\x06proto3')

_DEPLOYMENTTYPE = DESCRIPTOR.enum_types_by_name['DeploymentType']
DeploymentType = enum_type_wrapper.EnumTypeWrapper(_DEPLOYMENTTYPE)
UNKNOWN_DEPLOYMENTTYPE = 0
LOCAL = 1
DOCKER = 2


_CONFIG = DESCRIPTOR.message_types_by_name['Config']
_WEBEZYMONITOR = DESCRIPTOR.message_types_by_name['WebezyMonitor']


@overload
class WebezyMonitor:
	"""webezyio generated message [webezy.WebezyConfig.v1.WebezyMonitor]
	A class respresent a WebezyMonitor type
	"""
	prometheus = WebezyPrometheus__pb2.Config # type: WebezyPrometheus__pb2.Config

	def __init__(self, prometheus=WebezyPrometheus__pb2.Config):
		pass
WebezyMonitor = _reflection.GeneratedProtocolMessageType('WebezyMonitor', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYMONITOR,
  '__module__' : 'WebezyConfig_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.WebezyMonitor)
  })
_sym_db.RegisterMessage(WebezyMonitor)

@overload
class Config:
	"""webezyio generated message [webezy.WebezyConfig.v1.Config]
	A class respresent a Config type
	"""
	host = str # type: str
	port = int # type: int
	deployment = enum_type_wrapper.EnumTypeWrapper # type: enum_type_wrapper.EnumTypeWrapper
	proxy = WebezyProxy__pb2.Config # type: WebezyProxy__pb2.Config
	docs = google_dot_protobuf_dot_struct__pb2.Struct # type: google_dot_protobuf_dot_struct__pb2.Struct
	template = WebezyTemplate__pb2.Config # type: WebezyTemplate__pb2.Config
	monitor = WebezyMonitor # type: WebezyMonitor
	analytics = bool # type: bool
	token = str # type: str
	first_run = bool # type: bool
	webezyio_templates = List[str] # type: List[str]

	def __init__(self, host=str, port=int, deployment=enum_type_wrapper.EnumTypeWrapper, proxy=WebezyProxy__pb2.Config, docs=google_dot_protobuf_dot_struct__pb2.Struct, template=WebezyTemplate__pb2.Config, monitor=WebezyMonitor, analytics=bool, token=str, first_run=bool, webezyio_templates=List[str]):
		pass
Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'WebezyConfig_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyConfig.v1.Config)
  })
_sym_db.RegisterMessage(Config)


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEPLOYMENTTYPE._serialized_start=587
  _DEPLOYMENTTYPE._serialized_end=654
  _CONFIG._serialized_start=142
  _CONFIG._serialized_end=512
  _WEBEZYMONITOR._serialized_start=514
  _WEBEZYMONITOR._serialized_end=585
# @@protoc_insertion_point(module_scope)
