# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyTemplate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WebezyTemplate.proto\x12\x18webezy.WebezyTemplate.v1\"\x9b\x01\n\x0eTemplateConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08out_path\x18\x02 \x01(\t\x12\x0f\n\x07include\x18\x03 \x03(\t\x12\x0f\n\x07\x65xclude\x18\x04 \x03(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x07 \x01(\t\x12\x14\n\x0cinclude_code\x18\x08 \x01(\x08\"?\n\x13WebezyMethodContext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"o\n\x11WebezyFileContext\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12>\n\x07methods\x18\x02 \x03(\x0b\x32-.webezy.WebezyTemplate.v1.WebezyMethodContext\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x0c\"K\n\rWebezyContext\x12:\n\x05\x66iles\x18\x01 \x03(\x0b\x32+.webezy.WebezyTemplate.v1.WebezyFileContextb\x06proto3')



_TEMPLATECONFIG = DESCRIPTOR.message_types_by_name['TemplateConfig']
_WEBEZYMETHODCONTEXT = DESCRIPTOR.message_types_by_name['WebezyMethodContext']
_WEBEZYFILECONTEXT = DESCRIPTOR.message_types_by_name['WebezyFileContext']
_WEBEZYCONTEXT = DESCRIPTOR.message_types_by_name['WebezyContext']
TemplateConfig = _reflection.GeneratedProtocolMessageType('TemplateConfig', (_message.Message,), {
  'DESCRIPTOR' : _TEMPLATECONFIG,
  '__module__' : 'WebezyTemplate_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyTemplate.v1.TemplateConfig)
  })
_sym_db.RegisterMessage(TemplateConfig)

WebezyMethodContext = _reflection.GeneratedProtocolMessageType('WebezyMethodContext', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYMETHODCONTEXT,
  '__module__' : 'WebezyTemplate_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyTemplate.v1.WebezyMethodContext)
  })
_sym_db.RegisterMessage(WebezyMethodContext)

WebezyFileContext = _reflection.GeneratedProtocolMessageType('WebezyFileContext', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYFILECONTEXT,
  '__module__' : 'WebezyTemplate_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyTemplate.v1.WebezyFileContext)
  })
_sym_db.RegisterMessage(WebezyFileContext)

WebezyContext = _reflection.GeneratedProtocolMessageType('WebezyContext', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYCONTEXT,
  '__module__' : 'WebezyTemplate_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyTemplate.v1.WebezyContext)
  })
_sym_db.RegisterMessage(WebezyContext)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPLATECONFIG._serialized_start=51
  _TEMPLATECONFIG._serialized_end=206
  _WEBEZYMETHODCONTEXT._serialized_start=208
  _WEBEZYMETHODCONTEXT._serialized_end=271
  _WEBEZYFILECONTEXT._serialized_start=273
  _WEBEZYFILECONTEXT._serialized_end=384
  _WEBEZYCONTEXT._serialized_start=386
  _WEBEZYCONTEXT._serialized_end=461
# @@protoc_insertion_point(module_scope)
