# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyJson.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyConfig_pb2 as WebezyConfig__pb2
from . import WebezyCore_pb2 as WebezyCore__pb2
from . import WebezyService_pb2 as WebezyService__pb2
from . import WebezyPackage_pb2 as WebezyPackage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10WebezyJson.proto\x12\x14webezy.WebezyJson.v1\x1a\x12WebezyConfig.proto\x1a\x10WebezyCore.proto\x1a\x13WebezyService.proto\x1a\x13WebezyPackage.proto\"\xbe\x03\n\nWebezyJson\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x34\n\x07project\x18\x02 \x01(\x0b\x32#.webezy.WebezyCore.v1.WebezyProject\x12\x34\n\x06\x63onfig\x18\x03 \x01(\x0b\x32$.webezy.WebezyConfig.v1.WebezyConfig\x12@\n\x08services\x18\x04 \x03(\x0b\x32..webezy.WebezyJson.v1.WebezyJson.ServicesEntry\x12@\n\x08packages\x18\x05 \x03(\x0b\x32..webezy.WebezyJson.v1.WebezyJson.PackagesEntry\x1aW\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.webezy.WebezyService.v1.WebezyService:\x02\x38\x01\x1aW\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x35\n\x05value\x18\x02 \x01(\x0b\x32&.webezy.WebezyPackage.v1.WebezyPackage:\x02\x38\x01\x62\x06proto3')



_WEBEZYJSON = DESCRIPTOR.message_types_by_name['WebezyJson']
_WEBEZYJSON_SERVICESENTRY = _WEBEZYJSON.nested_types_by_name['ServicesEntry']
_WEBEZYJSON_PACKAGESENTRY = _WEBEZYJSON.nested_types_by_name['PackagesEntry']

@overload
class WebezyJson(_message.Message):
	"""webezyio generated message [webezy.WebezyJson.v1.WebezyJson]
	A class respresent a WebezyJson type
	The webezy.json file schema
		"""
	domain = str # type: str
	project = WebezyCore__pb2.WebezyProject # type: WebezyCore__pb2.WebezyProject
	config = WebezyConfig__pb2.WebezyConfig # type: WebezyConfig__pb2.WebezyConfig
	services = Dict[str,WebezyService__pb2.WebezyService] # type: Dict[str,WebezyService__pb2.WebezyService]
	packages = Dict[str,WebezyPackage__pb2.WebezyPackage] # type: Dict[str,WebezyPackage__pb2.WebezyPackage]

	def __init__(self, domain=str, project=WebezyCore__pb2.WebezyProject, config=WebezyConfig__pb2.WebezyConfig, services=Dict[str,WebezyService__pb2.WebezyService], packages=Dict[str,WebezyPackage__pb2.WebezyPackage]):
		"""
		Attributes:
		----------
		domain : str
			The domain name without any prefix or suffix
		project : WebezyCore__pb2.WebezyProject
			The webezy project description
		config : WebezyConfig__pb2.WebezyConfig
			The webezy project configs
		services : Dict[str,WebezyService__pb2.WebezyService]
			
		packages : Dict[str,WebezyPackage__pb2.WebezyPackage]
			
		"""
		pass
WebezyJson = _reflection.GeneratedProtocolMessageType('WebezyJson', (_message.Message,), {

  'ServicesEntry' : _reflection.GeneratedProtocolMessageType('ServicesEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEBEZYJSON_SERVICESENTRY,
    '__module__' : 'WebezyJson_pb2'
    # @@protoc_insertion_point(class_scope:webezy.WebezyJson.v1.WebezyJson.ServicesEntry)
    })
  ,

  'PackagesEntry' : _reflection.GeneratedProtocolMessageType('PackagesEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEBEZYJSON_PACKAGESENTRY,
    '__module__' : 'WebezyJson_pb2'
    # @@protoc_insertion_point(class_scope:webezy.WebezyJson.v1.WebezyJson.PackagesEntry)
    })
  ,
  'DESCRIPTOR' : _WEBEZYJSON,
  '__module__' : 'WebezyJson_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyJson.v1.WebezyJson)
  })
_sym_db.RegisterMessage(WebezyJson)
_sym_db.RegisterMessage(WebezyJson.ServicesEntry)
_sym_db.RegisterMessage(WebezyJson.PackagesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBEZYJSON_SERVICESENTRY._options = None
  _WEBEZYJSON_SERVICESENTRY._serialized_options = b'8\001'
  _WEBEZYJSON_PACKAGESENTRY._options = None
  _WEBEZYJSON_PACKAGESENTRY._serialized_options = b'8\001'
  _WEBEZYJSON._serialized_start=123
  _WEBEZYJSON._serialized_end=569
  _WEBEZYJSON_SERVICESENTRY._serialized_start=393
  _WEBEZYJSON_SERVICESENTRY._serialized_end=480
  _WEBEZYJSON_PACKAGESENTRY._serialized_start=482
  _WEBEZYJSON_PACKAGESENTRY._serialized_end=569
# @@protoc_insertion_point(module_scope)
