# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13WebezyService.proto\x12\x17webezy.WebezyService.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe0\x02\n\x0cWebezyMethod\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0c\n\x04kind\x18\x05 \x01(\t\x12\x12\n\ninput_type\x18\x06 \x01(\t\x12\x13\n\x0boutput_type\x18\x07 \x01(\t\x12\x18\n\x10\x63lient_streaming\x18\x08 \x01(\x08\x12\x18\n\x10server_streaming\x18\t \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12I\n\nextensions\x18\x0b \x03(\x0b\x32\x35.webezy.WebezyService.v1.WebezyMethod.ExtensionsEntry\x1aI\n\x0f\x45xtensionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\"\xe4\x02\n\rWebezyService\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x36\n\x07methods\x18\x04 \x03(\x0b\x32%.webezy.WebezyService.v1.WebezyMethod\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x06 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x0c\n\x04kind\x18\t \x01(\t\x12J\n\nextensions\x18\n \x03(\x0b\x32\x36.webezy.WebezyService.v1.WebezyService.ExtensionsEntry\x1aI\n\x0f\x45xtensionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01\x62\x06proto3')



_WEBEZYMETHOD = DESCRIPTOR.message_types_by_name['WebezyMethod']
_WEBEZYMETHOD_EXTENSIONSENTRY = _WEBEZYMETHOD.nested_types_by_name['ExtensionsEntry']
_WEBEZYSERVICE = DESCRIPTOR.message_types_by_name['WebezyService']
_WEBEZYSERVICE_EXTENSIONSENTRY = _WEBEZYSERVICE.nested_types_by_name['ExtensionsEntry']
WebezyMethod = _reflection.GeneratedProtocolMessageType('WebezyMethod', (_message.Message,), {

  'ExtensionsEntry' : _reflection.GeneratedProtocolMessageType('ExtensionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEBEZYMETHOD_EXTENSIONSENTRY,
    '__module__' : 'WebezyService_pb2'
    # @@protoc_insertion_point(class_scope:webezy.WebezyService.v1.WebezyMethod.ExtensionsEntry)
    })
  ,
  'DESCRIPTOR' : _WEBEZYMETHOD,
  '__module__' : 'WebezyService_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyService.v1.WebezyMethod)
  })
_sym_db.RegisterMessage(WebezyMethod)
_sym_db.RegisterMessage(WebezyMethod.ExtensionsEntry)

WebezyService = _reflection.GeneratedProtocolMessageType('WebezyService', (_message.Message,), {

  'ExtensionsEntry' : _reflection.GeneratedProtocolMessageType('ExtensionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEBEZYSERVICE_EXTENSIONSENTRY,
    '__module__' : 'WebezyService_pb2'
    # @@protoc_insertion_point(class_scope:webezy.WebezyService.v1.WebezyService.ExtensionsEntry)
    })
  ,
  'DESCRIPTOR' : _WEBEZYSERVICE,
  '__module__' : 'WebezyService_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyService.v1.WebezyService)
  })
_sym_db.RegisterMessage(WebezyService)
_sym_db.RegisterMessage(WebezyService.ExtensionsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBEZYMETHOD_EXTENSIONSENTRY._options = None
  _WEBEZYMETHOD_EXTENSIONSENTRY._serialized_options = b'8\001'
  _WEBEZYSERVICE_EXTENSIONSENTRY._options = None
  _WEBEZYSERVICE_EXTENSIONSENTRY._serialized_options = b'8\001'
  _WEBEZYMETHOD._serialized_start=79
  _WEBEZYMETHOD._serialized_end=431
  _WEBEZYMETHOD_EXTENSIONSENTRY._serialized_start=358
  _WEBEZYMETHOD_EXTENSIONSENTRY._serialized_end=431
  _WEBEZYSERVICE._serialized_start=434
  _WEBEZYSERVICE._serialized_end=790
  _WEBEZYSERVICE_EXTENSIONSENTRY._serialized_start=358
  _WEBEZYSERVICE_EXTENSIONSENTRY._serialized_end=431
# @@protoc_insertion_point(module_scope)
