# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyProxy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11WebezyProxy.proto\x12\x15webezy.WebezyProxy.v1\"-\n\x0cProxyAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\":\n\x0eProxyStatsSink\x12\x18\n\x10tcp_cluster_name\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"S\n\rProxyListener\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x34\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32#.webezy.WebezyProxy.v1.ProxyAddress\"E\n\rProxyEndpoint\x12\x34\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32#.webezy.WebezyProxy.v1.ProxyAddress\"U\n\x0cProxyCluster\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x37\n\tendpoints\x18\x02 \x03(\x0b\x32$.webezy.WebezyProxy.v1.ProxyEndpoint\"\xe2\x01\n\x06\x43onfig\x12\x32\n\x05\x61\x64min\x18\x01 \x01(\x0b\x32#.webezy.WebezyProxy.v1.ProxyAddress\x12\x34\n\x05stats\x18\x02 \x01(\x0b\x32%.webezy.WebezyProxy.v1.ProxyStatsSink\x12\x37\n\tlisteners\x18\x03 \x03(\x0b\x32$.webezy.WebezyProxy.v1.ProxyListener\x12\x35\n\x08\x63lusters\x18\x04 \x03(\x0b\x32#.webezy.WebezyProxy.v1.ProxyClusterb\x06proto3')



_PROXYADDRESS = DESCRIPTOR.message_types_by_name['ProxyAddress']
_PROXYSTATSSINK = DESCRIPTOR.message_types_by_name['ProxyStatsSink']
_PROXYLISTENER = DESCRIPTOR.message_types_by_name['ProxyListener']
_PROXYENDPOINT = DESCRIPTOR.message_types_by_name['ProxyEndpoint']
_PROXYCLUSTER = DESCRIPTOR.message_types_by_name['ProxyCluster']
_CONFIG = DESCRIPTOR.message_types_by_name['Config']

@overload
class ProxyAddress:
	"""webezyio generated message [webezy.WebezyProxy.v1.ProxyAddress]
	A class respresent a ProxyAddress type
	"""
	address = str # type: str
	port = int # type: int

	def __init__(self, address=str, port=int):
		pass
ProxyAddress = _reflection.GeneratedProtocolMessageType('ProxyAddress', (_message.Message,), {
  'DESCRIPTOR' : _PROXYADDRESS,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.ProxyAddress)
  })
_sym_db.RegisterMessage(ProxyAddress)


@overload
class ProxyStatsSink:
	"""webezyio generated message [webezy.WebezyProxy.v1.ProxyStatsSink]
	A class respresent a ProxyStatsSink type
	"""
	tcp_cluster_name = str # type: str
	prefix = str # type: str

	def __init__(self, tcp_cluster_name=str, prefix=str):
		pass
ProxyStatsSink = _reflection.GeneratedProtocolMessageType('ProxyStatsSink', (_message.Message,), {
  'DESCRIPTOR' : _PROXYSTATSSINK,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.ProxyStatsSink)
  })
_sym_db.RegisterMessage(ProxyStatsSink)


@overload
class ProxyListener:
	"""webezyio generated message [webezy.WebezyProxy.v1.ProxyListener]
	A class respresent a ProxyListener type
	"""
	name = str # type: str
	address = ProxyAddress # type: ProxyAddress

	def __init__(self, name=str, address=ProxyAddress):
		pass
ProxyListener = _reflection.GeneratedProtocolMessageType('ProxyListener', (_message.Message,), {
  'DESCRIPTOR' : _PROXYLISTENER,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.ProxyListener)
  })
_sym_db.RegisterMessage(ProxyListener)


@overload
class ProxyEndpoint:
	"""webezyio generated message [webezy.WebezyProxy.v1.ProxyEndpoint]
	A class respresent a ProxyEndpoint type
	"""
	address = ProxyAddress # type: ProxyAddress

	def __init__(self, address=ProxyAddress):
		pass
ProxyEndpoint = _reflection.GeneratedProtocolMessageType('ProxyEndpoint', (_message.Message,), {
  'DESCRIPTOR' : _PROXYENDPOINT,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.ProxyEndpoint)
  })
_sym_db.RegisterMessage(ProxyEndpoint)


@overload
class ProxyCluster:
	"""webezyio generated message [webezy.WebezyProxy.v1.ProxyCluster]
	A class respresent a ProxyCluster type
	"""
	name = str # type: str
	endpoints = List[ProxyEndpoint] # type: List[ProxyEndpoint]

	def __init__(self, name=str, endpoints=List[ProxyEndpoint]):
		pass
ProxyCluster = _reflection.GeneratedProtocolMessageType('ProxyCluster', (_message.Message,), {
  'DESCRIPTOR' : _PROXYCLUSTER,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.ProxyCluster)
  })
_sym_db.RegisterMessage(ProxyCluster)


@overload
class Config:
	"""webezyio generated message [webezy.WebezyProxy.v1.Config]
	A class respresent a Config type
	"""
	admin = ProxyAddress # type: ProxyAddress
	stats = ProxyStatsSink # type: ProxyStatsSink
	listeners = List[ProxyListener] # type: List[ProxyListener]
	clusters = List[ProxyCluster] # type: List[ProxyCluster]

	def __init__(self, admin=ProxyAddress, stats=ProxyStatsSink, listeners=List[ProxyListener], clusters=List[ProxyCluster]):
		pass
Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), {
  'DESCRIPTOR' : _CONFIG,
  '__module__' : 'WebezyProxy_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyProxy.v1.Config)
  })
_sym_db.RegisterMessage(Config)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROXYADDRESS._serialized_start=44
  _PROXYADDRESS._serialized_end=89
  _PROXYSTATSSINK._serialized_start=91
  _PROXYSTATSSINK._serialized_end=149
  _PROXYLISTENER._serialized_start=151
  _PROXYLISTENER._serialized_end=234
  _PROXYENDPOINT._serialized_start=236
  _PROXYENDPOINT._serialized_end=305
  _PROXYCLUSTER._serialized_start=307
  _PROXYCLUSTER._serialized_end=392
  _CONFIG._serialized_start=395
  _CONFIG._serialized_end=621
# @@protoc_insertion_point(module_scope)
