# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyCore.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10WebezyCore.proto\x12\x14webezy.WebezyCore.v1\x1a\x1cgoogle/protobuf/struct.proto\"-\n\nOkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"F\n\x0cWebezyServer\x12\x36\n\x08language\x18\x01 \x01(\x0e\x32$.webezy.WebezyCore.v1.WebezyLanguage\"9\n\tWebezyNpm\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0e\n\x06public\x18\x02 \x01(\x08\x12\r\n\x05token\x18\x03 \x01(\t\"\x92\x01\n\x0cWebezyClient\x12\x36\n\x08language\x18\x01 \x01(\x0e\x32$.webezy.WebezyCore.v1.WebezyLanguage\x12\x0f\n\x07out_dir\x18\x02 \x01(\t\x12.\n\x03npm\x18\x03 \x01(\x0b\x32\x1f.webezy.WebezyCore.v1.WebezyNpmH\x00\x42\t\n\x07package\"\x97\x02\n\rWebezyProject\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cpackage_name\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x0c\n\x04kind\x18\x06 \x01(\t\x12+\n\nproperties\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x32\n\x06server\x18\x08 \x01(\x0b\x32\".webezy.WebezyCore.v1.WebezyServer\x12\x33\n\x07\x63lients\x18\t \x03(\x0b\x32\".webezy.WebezyCore.v1.WebezyClient\x12\x12\n\ngo_package\x18\n \x01(\t*\x83\x01\n\x0eWebezyLanguage\x12\x1a\n\x16UNKNOWN_WEBEZYLANGUAGE\x10\x00\x12\n\n\x06python\x10\x01\x12\x0e\n\ntypescript\x10\x02\x12\x06\n\x02go\x10\x03\x12\x0b\n\x07webpack\x10\x04\x12\x0e\n\njavascript\x10\x05\x12\n\n\x06\x63sharp\x10\x06\x12\x08\n\x04java\x10\x07\x62\x06proto3')

_WEBEZYLANGUAGE = DESCRIPTOR.enum_types_by_name['WebezyLanguage']
WebezyLanguage = enum_type_wrapper.EnumTypeWrapper(_WEBEZYLANGUAGE)
UNKNOWN_WEBEZYLANGUAGE = 0
python = 1
typescript = 2
go = 3
webpack = 4
javascript = 5
csharp = 6
java = 7


_OKRESPONSE = DESCRIPTOR.message_types_by_name['OkResponse']
_WEBEZYSERVER = DESCRIPTOR.message_types_by_name['WebezyServer']
_WEBEZYNPM = DESCRIPTOR.message_types_by_name['WebezyNpm']
_WEBEZYCLIENT = DESCRIPTOR.message_types_by_name['WebezyClient']
_WEBEZYPROJECT = DESCRIPTOR.message_types_by_name['WebezyProject']

@overload
class OkResponse(_message.Message):
	"""webezyio generated message [webezy.WebezyCore.v1.OkResponse]
	A class respresent a OkResponse type
	This is OK Status response for RPC which excute a process
		"""
	status = str # type: str
	context = str # type: str

	def __init__(self, status=str, context=str):
		"""
		Attributes:
		----------
		status : str
			Should be OK for succssfull process
		context : str
			A human readable context for the process if any message should be more then just "OK"
		"""
		pass
OkResponse = _reflection.GeneratedProtocolMessageType('OkResponse', (_message.Message,), {
  'DESCRIPTOR' : _OKRESPONSE,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.OkResponse)
  })
_sym_db.RegisterMessage(OkResponse)


@overload
class WebezyServer(_message.Message):
	"""webezyio generated message [webezy.WebezyCore.v1.WebezyServer]
	A class respresent a WebezyServer type
	The description for webezy server
		"""
	language = enum_type_wrapper.EnumTypeWrapper # type: enum_type_wrapper.EnumTypeWrapper

	def __init__(self, language=enum_type_wrapper.EnumTypeWrapper):
		"""
		Attributes:
		----------
		language : enum_type_wrapper.EnumTypeWrapper
			The server language
		"""
		pass
WebezyServer = _reflection.GeneratedProtocolMessageType('WebezyServer', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYSERVER,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.WebezyServer)
  })
_sym_db.RegisterMessage(WebezyServer)


@overload
class WebezyNpm(_message.Message):
	"""webezyio generated message [webezy.WebezyCore.v1.WebezyNpm]
	A class respresent a WebezyNpm type
	Webezy Node Package Manager integration configurations for wrapping the Typescript / Javascript packages directly to npm with every build command
		"""
	scope = str # type: str
	public = bool # type: bool
	token = str # type: str

	def __init__(self, scope=str, public=bool, token=str):
		"""
		Attributes:
		----------
		scope : str
			The user or organization scope see: https://docs.npmjs.com/about-scopes
		public : bool
			If package access is public see: https://docs.npmjs.com/about-public-packages
		token : str
			The npm access token see: https://docs.npmjs.com/creating-and-viewing-access-tokens
		"""
		pass
WebezyNpm = _reflection.GeneratedProtocolMessageType('WebezyNpm', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYNPM,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.WebezyNpm)
  })
_sym_db.RegisterMessage(WebezyNpm)


@overload
class WebezyClient(_message.Message):
	"""webezyio generated message [webezy.WebezyCore.v1.WebezyClient]
	A class respresent a WebezyClient type
	The description for webezy client
		"""
	language = enum_type_wrapper.EnumTypeWrapper # type: enum_type_wrapper.EnumTypeWrapper
	out_dir = str # type: str
	npm = WebezyNpm # type: WebezyNpm

	def __init__(self, language=enum_type_wrapper.EnumTypeWrapper, out_dir=str, npm=WebezyNpm):
		"""
		Attributes:
		----------
		language : enum_type_wrapper.EnumTypeWrapper
			The client language
		out_dir : str
			The output path for the client code modules
		package : None
			Client package configurations for 3rd parties
		"""
		pass
WebezyClient = _reflection.GeneratedProtocolMessageType('WebezyClient', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYCLIENT,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.WebezyClient)
  })
_sym_db.RegisterMessage(WebezyClient)


@overload
class WebezyProject(_message.Message):
	"""webezyio generated message [webezy.WebezyCore.v1.WebezyProject]
	A class respresent a WebezyProject type
	The webezy project description
		"""
	uri = str # type: str
	name = str # type: str
	package_name = str # type: str
	version = str # type: str
	type = str # type: str
	kind = str # type: str
	properties = google_dot_protobuf_dot_struct__pb2.Struct # type: google_dot_protobuf_dot_struct__pb2.Struct
	server = WebezyServer # type: WebezyServer
	clients = List[WebezyClient] # type: List[WebezyClient]
	go_package = str # type: str

	def __init__(self, uri=str, name=str, package_name=str, version=str, type=str, kind=str, properties=google_dot_protobuf_dot_struct__pb2.Struct, server=WebezyServer, clients=List[WebezyClient], go_package=str):
		"""
		Attributes:
		----------
		uri : str
			The project URI of root directory where the webezy.json file exists
		name : str
			Project full display name
		package_name : str
			project name code compatiable
		version : str
			The project version following SEMVER semantics
		type : str
			The project resource type
		kind : str
			The project resource kind
		properties : google_dot_protobuf_dot_struct__pb2.Struct
			Additional project properties
		server : WebezyServer
			The project attached server descriptin
		clients : List[WebezyClient]
			The project assigned clients array
		go_package : str
			The go compatiable package name
		"""
		pass
WebezyProject = _reflection.GeneratedProtocolMessageType('WebezyProject', (_message.Message,), {
  'DESCRIPTOR' : _WEBEZYPROJECT,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.WebezyProject)
  })
_sym_db.RegisterMessage(WebezyProject)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEBEZYLANGUAGE._serialized_start=682
  _WEBEZYLANGUAGE._serialized_end=813
  _OKRESPONSE._serialized_start=72
  _OKRESPONSE._serialized_end=117
  _WEBEZYSERVER._serialized_start=119
  _WEBEZYSERVER._serialized_end=189
  _WEBEZYNPM._serialized_start=191
  _WEBEZYNPM._serialized_end=248
  _WEBEZYCLIENT._serialized_start=251
  _WEBEZYCLIENT._serialized_end=397
  _WEBEZYPROJECT._serialized_start=400
  _WEBEZYPROJECT._serialized_end=679
# @@protoc_insertion_point(module_scope)
