# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import OtherPackage_pb2 as OtherPackage__pb2
from . import SamplePackage_pb2 as SamplePackage__pb2


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleRPC = channel.unary_unary(
                '/SampleService/SampleRPC',
                request_serializer=SamplePackage__pb2.SampleMessage.SerializeToString,
                response_deserializer=SamplePackage__pb2.SampleMessage.FromString,
                )
        self.TestRPC = channel.stream_unary(
                '/SampleService/TestRPC',
                request_serializer=OtherPackage__pb2.OtherMessage.SerializeToString,
                response_deserializer=OtherPackage__pb2.OtherMessage.FromString,
                )
        self.OtherRPC = channel.stream_unary(
                '/SampleService/OtherRPC',
                request_serializer=OtherPackage__pb2.OtherMessage.SerializeToString,
                response_deserializer=SamplePackage__pb2.SampleMessage.FromString,
                )


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SampleRPC(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestRPC(self, request_iterator, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OtherRPC(self, request_iterator, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleRPC,
                    request_deserializer=SamplePackage__pb2.SampleMessage.FromString,
                    response_serializer=SamplePackage__pb2.SampleMessage.SerializeToString,
            ),
            'TestRPC': grpc.stream_unary_rpc_method_handler(
                    servicer.TestRPC,
                    request_deserializer=OtherPackage__pb2.OtherMessage.FromString,
                    response_serializer=OtherPackage__pb2.OtherMessage.SerializeToString,
            ),
            'OtherRPC': grpc.stream_unary_rpc_method_handler(
                    servicer.OtherRPC,
                    request_deserializer=OtherPackage__pb2.OtherMessage.FromString,
                    response_serializer=SamplePackage__pb2.SampleMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SampleRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SampleService/SampleRPC',
            SamplePackage__pb2.SampleMessage.SerializeToString,
            SamplePackage__pb2.SampleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestRPC(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SampleService/TestRPC',
            OtherPackage__pb2.OtherMessage.SerializeToString,
            OtherPackage__pb2.OtherMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def OtherRPC(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/SampleService/OtherRPC',
            OtherPackage__pb2.OtherMessage.SerializeToString,
            SamplePackage__pb2.SampleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
