# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SamplePackage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import OtherPackage_pb2 as OtherPackage__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SamplePackage.proto\x12\x17webezy.SamplePackage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12OtherPackage.proto\x1a google/protobuf/descriptor.proto\"\xf8\x04\n\rSampleMessage\x12\x1f\n\rExtendedField\x18\x01 \x01(\x08\x42\x08\xa0\x90\x1b\x00\xa0\x90\x1b\x01\x12-\n\tTimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x07Integer\x18\x03 \x01(\x05\x42\x08\xaa\x90\x1b\x04Test\x12:\n\x0c\x43hildMessage\x18\x04 \x01(\x0b\x32$.webezy.OtherPackage.v1.OtherMessage\x12>\n\x04test\x18\x05 \x03(\x0b\x32\x30.webezy.SamplePackage.v1.SampleMessage.TestEntry\x12P\n\rtestNestedMap\x18\x06 \x03(\x0b\x32\x39.webezy.SamplePackage.v1.SampleMessage.TestNestedMapEntry\x12L\n\x0btestEnumMap\x18\x07 \x03(\x0b\x32\x37.webezy.SamplePackage.v1.SampleMessage.TestEnumMapEntry\x1a+\n\tTestEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aZ\n\x12TestNestedMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x33\n\x05value\x18\x02 \x01(\x0b\x32$.webezy.OtherPackage.v1.OtherMessage:\x02\x38\x01\x1aW\n\x10TestEnumMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0e\x32#.webezy.SamplePackage.v1.SampleEnum:\x02\x38\x01\"|\n\x10\x45xtensionMessage23\n\nBoolExtend\x12\x1d.google.protobuf.FieldOptions\x18\x84\xb2\x03 \x03(\x08\x32\x33\n\nTestString\x12\x1d.google.protobuf.FieldOptions\x18\x85\xb2\x03 \x01(\t*#\n\nSampleEnum\x12\x0b\n\x07UNKNWON\x10\x00\x12\x08\n\x04TEST\x10\x01\x62\x06proto3')

_SAMPLEENUM = DESCRIPTOR.enum_types_by_name['SampleEnum']
SampleEnum = enum_type_wrapper.EnumTypeWrapper(_SAMPLEENUM)
UNKNWON = 0
TEST = 1


_SAMPLEMESSAGE = DESCRIPTOR.message_types_by_name['SampleMessage']
_SAMPLEMESSAGE_TESTENTRY = _SAMPLEMESSAGE.nested_types_by_name['TestEntry']
_SAMPLEMESSAGE_TESTNESTEDMAPENTRY = _SAMPLEMESSAGE.nested_types_by_name['TestNestedMapEntry']
_SAMPLEMESSAGE_TESTENUMMAPENTRY = _SAMPLEMESSAGE.nested_types_by_name['TestEnumMapEntry']
_EXTENSIONMESSAGE = DESCRIPTOR.message_types_by_name['ExtensionMessage']

@overload
class SampleMessage:
	"""webezyio generated message [webezy.SamplePackage.v1.SampleMessage]
	A class respresent a SampleMessage type
	"""
	ExtendedField = bool # type: bool
	Timestamp = google_dot_protobuf_dot_timestamp__pb2.Timestamp # type: google_dot_protobuf_dot_timestamp__pb2.Timestamp
	Integer = int # type: int
	ChildMessage = OtherPackage__pb2.OtherMessage # type: OtherPackage__pb2.OtherMessage
	test = Dict[str,str] # type: Dict[str,str]
	testNestedMap = Dict[str,OtherPackage__pb2.OtherMessage] # type: Dict[str,OtherPackage__pb2.OtherMessage]
	testEnumMap = Dict[str,SampleEnum] # type: Dict[str,SampleEnum]

	def __init__(self, ExtendedField=bool, Timestamp=google_dot_protobuf_dot_timestamp__pb2.Timestamp, Integer=int, ChildMessage=OtherPackage__pb2.OtherMessage, test=Dict[str,str], testNestedMap=Dict[str,OtherPackage__pb2.OtherMessage], testEnumMap=Dict[str,SampleEnum]):
		pass
SampleMessage = _reflection.GeneratedProtocolMessageType('SampleMessage', (_message.Message,), {

  'TestEntry' : _reflection.GeneratedProtocolMessageType('TestEntry', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLEMESSAGE_TESTENTRY,
    '__module__' : 'SamplePackage_pb2'
    # @@protoc_insertion_point(class_scope:webezy.SamplePackage.v1.SampleMessage.TestEntry)
    })
  ,

  'TestNestedMapEntry' : _reflection.GeneratedProtocolMessageType('TestNestedMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLEMESSAGE_TESTNESTEDMAPENTRY,
    '__module__' : 'SamplePackage_pb2'
    # @@protoc_insertion_point(class_scope:webezy.SamplePackage.v1.SampleMessage.TestNestedMapEntry)
    })
  ,

  'TestEnumMapEntry' : _reflection.GeneratedProtocolMessageType('TestEnumMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _SAMPLEMESSAGE_TESTENUMMAPENTRY,
    '__module__' : 'SamplePackage_pb2'
    # @@protoc_insertion_point(class_scope:webezy.SamplePackage.v1.SampleMessage.TestEnumMapEntry)
    })
  ,
  'DESCRIPTOR' : _SAMPLEMESSAGE,
  '__module__' : 'SamplePackage_pb2'
  # @@protoc_insertion_point(class_scope:webezy.SamplePackage.v1.SampleMessage)
  })
_sym_db.RegisterMessage(SampleMessage)
_sym_db.RegisterMessage(SampleMessage.TestEntry)
_sym_db.RegisterMessage(SampleMessage.TestNestedMapEntry)
_sym_db.RegisterMessage(SampleMessage.TestEnumMapEntry)


@overload
class ExtensionMessage:
	"""webezyio generated message [webezy.SamplePackage.v1.ExtensionMessage]
	A class respresent a ExtensionMessage type
	"""
	BoolExtend = List[bool] # type: List[bool]
	TestString = str # type: str

	def __init__(self, BoolExtend=List[bool], TestString=str):
		pass
ExtensionMessage = _reflection.GeneratedProtocolMessageType('ExtensionMessage', (_message.Message,), {
  'DESCRIPTOR' : _EXTENSIONMESSAGE,
  '__module__' : 'SamplePackage_pb2'
  # @@protoc_insertion_point(class_scope:webezy.SamplePackage.v1.ExtensionMessage)
  })
_sym_db.RegisterMessage(ExtensionMessage)

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(_EXTENSIONMESSAGE.extensions_by_name['BoolExtend'])
  google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(_EXTENSIONMESSAGE.extensions_by_name['TestString'])

  DESCRIPTOR._options = None
  _SAMPLEMESSAGE_TESTENTRY._options = None
  _SAMPLEMESSAGE_TESTENTRY._serialized_options = b'8\001'
  _SAMPLEMESSAGE_TESTNESTEDMAPENTRY._options = None
  _SAMPLEMESSAGE_TESTNESTEDMAPENTRY._serialized_options = b'8\001'
  _SAMPLEMESSAGE_TESTENUMMAPENTRY._options = None
  _SAMPLEMESSAGE_TESTENUMMAPENTRY._serialized_options = b'8\001'
  _SAMPLEMESSAGE.fields_by_name['ExtendedField']._options = None
  _SAMPLEMESSAGE.fields_by_name['ExtendedField']._serialized_options = b'\240\220\033\000\240\220\033\001'
  _SAMPLEMESSAGE.fields_by_name['Integer']._options = None
  _SAMPLEMESSAGE.fields_by_name['Integer']._serialized_options = b'\252\220\033\004Test'
  _SAMPLEENUM._serialized_start=896
  _SAMPLEENUM._serialized_end=931
  _SAMPLEMESSAGE._serialized_start=136
  _SAMPLEMESSAGE._serialized_end=768
  _SAMPLEMESSAGE_TESTENTRY._serialized_start=544
  _SAMPLEMESSAGE_TESTENTRY._serialized_end=587
  _SAMPLEMESSAGE_TESTNESTEDMAPENTRY._serialized_start=589
  _SAMPLEMESSAGE_TESTNESTEDMAPENTRY._serialized_end=679
  _SAMPLEMESSAGE_TESTENUMMAPENTRY._serialized_start=681
  _SAMPLEMESSAGE_TESTENUMMAPENTRY._serialized_end=768
  _EXTENSIONMESSAGE._serialized_start=770
  _EXTENSIONMESSAGE._serialized_end=894
# @@protoc_insertion_point(module_scope)
