# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkProject.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import SylkClient_pb2 as SylkClient__pb2
from . import SylkServer_pb2 as SylkServer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SylkProject.proto\x12\x13sylk.SylkProject.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x10SylkClient.proto\x1a\x10SylkServer.proto\"\x85\x02\n\x0bSylkProject\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cpackage_name\x18\x03 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12/\n\x07\x63lients\x18\x06 \x03(\x0b\x32\x1e.sylk.SylkClient.v1.SylkClient\x12.\n\x06server\x18\x07 \x01(\x0b\x32\x1e.sylk.SylkServer.v1.SylkServer\x12\x0f\n\x07version\x18\x08 \x01(\t\x12\x0c\n\x04type\x18\t \x01(\t\x12\x0c\n\x04kind\x18\n \x01(\t\x12\x12\n\ngo_package\x18\x0b \x01(\tB2Z0github.com/sylk/core/services/protos/SylkProjectb\x06proto3')



_SYLKPROJECT = DESCRIPTOR.message_types_by_name['SylkProject']

@overload
class SylkProject(_message.Message):
	"""webezyio generated message [sylk.SylkProject.v1.SylkProject]
	A class respresent a SylkProject type
	
	"""
	uri = str # type: str
	name = str # type: str
	package_name = str # type: str
	author = str # type: str
	description = str # type: str
	clients = List[SylkClient__pb2.SylkClient] # type: List[SylkClient__pb2.SylkClient]
	server = SylkServer__pb2.SylkServer # type: SylkServer__pb2.SylkServer
	version = str # type: str
	type = str # type: str
	kind = str # type: str
	go_package = str # type: str

	def __init__(self, uri=str, name=str, package_name=str, author=str, description=str, clients=List[SylkClient__pb2.SylkClient], server=SylkServer__pb2.SylkServer, version=str, type=str, kind=str, go_package=str):
		"""
		Attributes:
		----------
		uri : str
			
		name : str
			
		package_name : str
			
		author : str
			
		description : str
			
		clients : List[SylkClient__pb2.SylkClient]
			
		server : SylkServer__pb2.SylkServer
			
		version : str
			
		type : str
			
		kind : str
			
		go_package : str
			
		"""
		pass
SylkProject = _reflection.GeneratedProtocolMessageType('SylkProject', (_message.Message,), {
  'DESCRIPTOR' : _SYLKPROJECT,
  '__module__' : 'SylkProject_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkProject.v1.SylkProject)
  })
_sym_db.RegisterMessage(SylkProject)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/sylk/core/services/protos/SylkProject'
  _SYLKPROJECT._serialized_start=109
  _SYLKPROJECT._serialized_end=370
# @@protoc_insertion_point(module_scope)
