# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkOrganization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16SylkOrganization.proto\x12\x18sylk.SylkOrganization.v1\".\n\x10SylkOrganization\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\tB7Z5github.com/sylk/core/services/protos/SylkOrganizationb\x06proto3')



_SYLKORGANIZATION = DESCRIPTOR.message_types_by_name['SylkOrganization']

@overload
class SylkOrganization(_message.Message):
	"""webezyio generated message [sylk.SylkOrganization.v1.SylkOrganization]
	A class respresent a SylkOrganization type
	
	"""
	id = str # type: str
	domain = str # type: str

	def __init__(self, id=str, domain=str):
		"""
		Attributes:
		----------
		id : str
			
		domain : str
			
		"""
		pass
SylkOrganization = _reflection.GeneratedProtocolMessageType('SylkOrganization', (_message.Message,), {
  'DESCRIPTOR' : _SYLKORGANIZATION,
  '__module__' : 'SylkOrganization_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkOrganization.v1.SylkOrganization)
  })
_sym_db.RegisterMessage(SylkOrganization)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/sylk/core/services/protos/SylkOrganization'
  _SYLKORGANIZATION._serialized_start=52
  _SYLKORGANIZATION._serialized_end=98
# @@protoc_insertion_point(module_scope)
