# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkConfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SylkConfig.proto\x12\x12sylk.SylkConfig.v1\x1a\x1cgoogle/protobuf/struct.proto\"y\n\x0eSylkCliConfigs\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x11\n\tanalytics\x18\x03 \x01(\x08\x12\x11\n\tfirst_run\x18\x04 \x01(\x08\x12\r\n\x05token\x18\x05 \x01(\t\x12\x16\n\x0esylk_templates\x18\x06 \x03(\t\"0\n\x12SylkProjectConfigs\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\xa0\x01\n\x13SylkTemplateConfigs\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08out_path\x18\x02 \x01(\t\x12\x0f\n\x07include\x18\x03 \x03(\t\x12\x0f\n\x07\x65xclude\x18\x04 \x03(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x07 \x01(\t\x12\x14\n\x0cinclude_code\x18\x08 \x01(\x08\x42\x31Z/github.com/sylk/core/services/protos/SylkConfigb\x06proto3')



_SYLKCLICONFIGS = DESCRIPTOR.message_types_by_name['SylkCliConfigs']
_SYLKPROJECTCONFIGS = DESCRIPTOR.message_types_by_name['SylkProjectConfigs']
_SYLKTEMPLATECONFIGS = DESCRIPTOR.message_types_by_name['SylkTemplateConfigs']

@overload
class SylkCliConfigs(_message.Message):
	"""webezyio generated message [sylk.SylkConfig.v1.SylkCliConfigs]
	A class respresent a SylkCliConfigs type
	
	"""
	host = str # type: str
	port = int # type: int
	analytics = bool # type: bool
	first_run = bool # type: bool
	token = str # type: str
	sylk_templates = List[str] # type: List[str]

	def __init__(self, host=str, port=int, analytics=bool, first_run=bool, token=str, sylk_templates=List[str]):
		"""
		Attributes:
		----------
		host : str
			
		port : int
			
		analytics : bool
			
		first_run : bool
			
		token : str
			
		sylk_templates : List[str]
			
		"""
		pass
SylkCliConfigs = _reflection.GeneratedProtocolMessageType('SylkCliConfigs', (_message.Message,), {
  'DESCRIPTOR' : _SYLKCLICONFIGS,
  '__module__' : 'SylkConfig_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkConfig.v1.SylkCliConfigs)
  })
_sym_db.RegisterMessage(SylkCliConfigs)


@overload
class SylkProjectConfigs(_message.Message):
	"""webezyio generated message [sylk.SylkConfig.v1.SylkProjectConfigs]
	A class respresent a SylkProjectConfigs type
	
	"""
	host = str # type: str
	port = int # type: int

	def __init__(self, host=str, port=int):
		"""
		Attributes:
		----------
		host : str
			
		port : int
			
		"""
		pass
SylkProjectConfigs = _reflection.GeneratedProtocolMessageType('SylkProjectConfigs', (_message.Message,), {
  'DESCRIPTOR' : _SYLKPROJECTCONFIGS,
  '__module__' : 'SylkConfig_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkConfig.v1.SylkProjectConfigs)
  })
_sym_db.RegisterMessage(SylkProjectConfigs)


@overload
class SylkTemplateConfigs(_message.Message):
	"""webezyio generated message [sylk.SylkConfig.v1.SylkTemplateConfigs]
	A class respresent a SylkTemplateConfigs type
	
	"""
	name = str # type: str
	out_path = str # type: str
	include = List[str] # type: List[str]
	exclude = List[str] # type: List[str]
	tags = List[str] # type: List[str]
	description = str # type: str
	author = str # type: str
	include_code = bool # type: bool

	def __init__(self, name=str, out_path=str, include=List[str], exclude=List[str], tags=List[str], description=str, author=str, include_code=bool):
		"""
		Attributes:
		----------
		name : str
			
		out_path : str
			
		include : List[str]
			
		exclude : List[str]
			
		tags : List[str]
			
		description : str
			
		author : str
			
		include_code : bool
			
		"""
		pass
SylkTemplateConfigs = _reflection.GeneratedProtocolMessageType('SylkTemplateConfigs', (_message.Message,), {
  'DESCRIPTOR' : _SYLKTEMPLATECONFIGS,
  '__module__' : 'SylkConfig_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkConfig.v1.SylkTemplateConfigs)
  })
_sym_db.RegisterMessage(SylkTemplateConfigs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/sylk/core/services/protos/SylkConfig'
  _SYLKCLICONFIGS._serialized_start=70
  _SYLKCLICONFIGS._serialized_end=191
  _SYLKPROJECTCONFIGS._serialized_start=193
  _SYLKPROJECTCONFIGS._serialized_end=241
  _SYLKTEMPLATECONFIGS._serialized_start=244
  _SYLKTEMPLATECONFIGS._serialized_end=404
# @@protoc_insertion_point(module_scope)
