# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from . import SylkMethod_pb2 as SylkMethod__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SylkService.proto\x12\x13sylk.SylkService.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x10SylkMethod.proto\"\xa9\x02\n\x0bSylkService\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12/\n\x07methods\x18\x04 \x03(\x0b\x32\x1e.sylk.SylkMethod.v1.SylkMethod\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x06 \x03(\t\x12\x44\n\nextensions\x18\x07 \x03(\x0b\x32\x30.sylk.SylkService.v1.SylkService.ExtensionsEntry\x1aJ\n\x0f\x45xtensionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x42\x32Z0github.com/sylk/core/services/protos/SylkServiceb\x06proto3')



_SYLKSERVICE = DESCRIPTOR.message_types_by_name['SylkService']
_SYLKSERVICE_EXTENSIONSENTRY = _SYLKSERVICE.nested_types_by_name['ExtensionsEntry']

@overload
class SylkService(_message.Message):
	"""webezyio generated message [sylk.SylkService.v1.SylkService]
	A class respresent a SylkService type
	
	"""
	uri = str # type: str
	name = str # type: str
	full_name = str # type: str
	methods = List[SylkMethod__pb2.SylkMethod] # type: List[SylkMethod__pb2.SylkMethod]
	description = str # type: str
	dependencies = List[str] # type: List[str]
	extensions = Dict[str,google_dot_protobuf_dot_struct__pb2.Struct] # type: Dict[str,google_dot_protobuf_dot_struct__pb2.Struct]

	def __init__(self, uri=str, name=str, full_name=str, methods=List[SylkMethod__pb2.SylkMethod], description=str, dependencies=List[str], extensions=Dict[str,google_dot_protobuf_dot_struct__pb2.Struct]):
		"""
		Attributes:
		----------
		uri : str
			
		name : str
			
		full_name : str
			
		methods : List[SylkMethod__pb2.SylkMethod]
			
		description : str
			
		dependencies : List[str]
			
		extensions : Dict[str,google_dot_protobuf_dot_struct__pb2.Struct]
			
		"""
		pass
SylkService = _reflection.GeneratedProtocolMessageType('SylkService', (_message.Message,), {

  'ExtensionsEntry' : _reflection.GeneratedProtocolMessageType('ExtensionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYLKSERVICE_EXTENSIONSENTRY,
    '__module__' : 'SylkService_pb2'
    # @@protoc_insertion_point(class_scope:sylk.SylkService.v1.SylkService.ExtensionsEntry)
    })
  ,
  'DESCRIPTOR' : _SYLKSERVICE,
  '__module__' : 'SylkService_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkService.v1.SylkService)
  })
_sym_db.RegisterMessage(SylkService)
_sym_db.RegisterMessage(SylkService.ExtensionsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/sylk/core/services/protos/SylkService'
  _SYLKSERVICE_EXTENSIONSENTRY._options = None
  _SYLKSERVICE_EXTENSIONSENTRY._serialized_options = b'8\001'
  _SYLKSERVICE._serialized_start=91
  _SYLKSERVICE._serialized_end=388
  _SYLKSERVICE_EXTENSIONSENTRY._serialized_start=314
  _SYLKSERVICE_EXTENSIONSENTRY._serialized_end=388
# @@protoc_insertion_point(module_scope)
