# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkClient.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SylkClient.proto\x12\x12sylk.SylkClient.v1\"T\n\nSylkClient\x12\x35\n\x08language\x18\x01 \x01(\x0e\x32#.sylk.SylkClient.v1.ClientLanguages\x12\x0f\n\x07out_dir\x18\x02 \x01(\t*^\n\x0f\x43lientLanguages\x12\x1b\n\x17UNKNOWN_CLIENTLANGUAGES\x10\x00\x12\n\n\x06python\x10\x01\x12\n\n\x06nodejs\x10\x02\x12\x0e\n\ntypescript\x10\x03\x12\x06\n\x02go\x10\x04\x42\x31Z/github.com/sylk/core/services/protos/SylkClientb\x06proto3')

_CLIENTLANGUAGES = DESCRIPTOR.enum_types_by_name['ClientLanguages']
ClientLanguages = enum_type_wrapper.EnumTypeWrapper(_CLIENTLANGUAGES)
UNKNOWN_CLIENTLANGUAGES = 0
python = 1
nodejs = 2
typescript = 3
go = 4


_SYLKCLIENT = DESCRIPTOR.message_types_by_name['SylkClient']

@overload
class SylkClient(_message.Message):
	"""webezyio generated message [sylk.SylkClient.v1.SylkClient]
	A class respresent a SylkClient type
	
	"""
	language = enum_type_wrapper.EnumTypeWrapper # type: enum_type_wrapper.EnumTypeWrapper
	out_dir = str # type: str

	def __init__(self, language=enum_type_wrapper.EnumTypeWrapper, out_dir=str):
		"""
		Attributes:
		----------
		language : enum_type_wrapper.EnumTypeWrapper
			
		out_dir : str
			
		"""
		pass
SylkClient = _reflection.GeneratedProtocolMessageType('SylkClient', (_message.Message,), {
  'DESCRIPTOR' : _SYLKCLIENT,
  '__module__' : 'SylkClient_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkClient.v1.SylkClient)
  })
_sym_db.RegisterMessage(SylkClient)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/sylk/core/services/protos/SylkClient'
  _CLIENTLANGUAGES._serialized_start=126
  _CLIENTLANGUAGES._serialized_end=220
  _SYLKCLIENT._serialized_start=40
  _SYLKCLIENT._serialized_end=124
# @@protoc_insertion_point(module_scope)
