# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkCore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SylkOrganization_pb2 as SylkOrganization__pb2
from . import SylkPackage_pb2 as SylkPackage__pb2
from . import SylkConfig_pb2 as SylkConfig__pb2
from . import SylkService_pb2 as SylkService__pb2
from . import SylkProject_pb2 as SylkProject__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSylkCore.proto\x12\x10sylk.SylkCore.v1\x1a\x16SylkOrganization.proto\x1a\x11SylkPackage.proto\x1a\x10SylkConfig.proto\x1a\x11SylkService.proto\x1a\x11SylkProject.proto\"\xdb\x03\n\x04Sylk\x12@\n\x0corganization\x18\x01 \x01(\x0b\x32*.sylk.SylkOrganization.v1.SylkOrganization\x12\x31\n\x07project\x18\x02 \x01(\x0b\x32 .sylk.SylkProject.v1.SylkProject\x12\x36\n\x08packages\x18\x03 \x03(\x0b\x32$.sylk.SylkCore.v1.Sylk.PackagesEntry\x12\x36\n\x08services\x18\x04 \x03(\x0b\x32$.sylk.SylkCore.v1.Sylk.ServicesEntry\x12\x36\n\x06\x63onfig\x18\x05 \x01(\x0b\x32&.sylk.SylkConfig.v1.SylkProjectConfigs\x12\x14\n\x0csylk_version\x18\x06 \x01(\t\x1aM\n\rPackagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.sylk.SylkPackage.v1.Package:\x02\x38\x01\x1aQ\n\rServicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .sylk.SylkService.v1.SylkService:\x02\x38\x01\x42/Z-github.com/sylk/core/services/protos/SylkCoreb\x06proto3')



_SYLK = DESCRIPTOR.message_types_by_name['Sylk']
_SYLK_PACKAGESENTRY = _SYLK.nested_types_by_name['PackagesEntry']
_SYLK_SERVICESENTRY = _SYLK.nested_types_by_name['ServicesEntry']

@overload
class Sylk(_message.Message):
	"""webezyio generated message [sylk.SylkCore.v1.Sylk]
	A class respresent a Sylk type
	
	"""
	organization = SylkOrganization__pb2.SylkOrganization # type: SylkOrganization__pb2.SylkOrganization
	project = SylkProject__pb2.SylkProject # type: SylkProject__pb2.SylkProject
	packages = Dict[str,SylkPackage__pb2.Package] # type: Dict[str,SylkPackage__pb2.Package]
	services = Dict[str,SylkService__pb2.SylkService] # type: Dict[str,SylkService__pb2.SylkService]
	config = SylkConfig__pb2.SylkProjectConfigs # type: SylkConfig__pb2.SylkProjectConfigs
	sylk_version = str # type: str

	def __init__(self, organization=SylkOrganization__pb2.SylkOrganization, project=SylkProject__pb2.SylkProject, packages=Dict[str,SylkPackage__pb2.Package], services=Dict[str,SylkService__pb2.SylkService], config=SylkConfig__pb2.SylkProjectConfigs, sylk_version=str):
		"""
		Attributes:
		----------
		organization : SylkOrganization__pb2.SylkOrganization
			
		project : SylkProject__pb2.SylkProject
			
		packages : Dict[str,SylkPackage__pb2.Package]
			
		services : Dict[str,SylkService__pb2.SylkService]
			
		config : SylkConfig__pb2.SylkProjectConfigs
			
		sylk_version : str
			
		"""
		pass
Sylk = _reflection.GeneratedProtocolMessageType('Sylk', (_message.Message,), {

  'PackagesEntry' : _reflection.GeneratedProtocolMessageType('PackagesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYLK_PACKAGESENTRY,
    '__module__' : 'SylkCore_pb2'
    # @@protoc_insertion_point(class_scope:sylk.SylkCore.v1.Sylk.PackagesEntry)
    })
  ,

  'ServicesEntry' : _reflection.GeneratedProtocolMessageType('ServicesEntry', (_message.Message,), {
    'DESCRIPTOR' : _SYLK_SERVICESENTRY,
    '__module__' : 'SylkCore_pb2'
    # @@protoc_insertion_point(class_scope:sylk.SylkCore.v1.Sylk.ServicesEntry)
    })
  ,
  'DESCRIPTOR' : _SYLK,
  '__module__' : 'SylkCore_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkCore.v1.Sylk)
  })
_sym_db.RegisterMessage(Sylk)
_sym_db.RegisterMessage(Sylk.PackagesEntry)
_sym_db.RegisterMessage(Sylk.ServicesEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z-github.com/sylk/core/services/protos/SylkCore'
  _SYLK_PACKAGESENTRY._options = None
  _SYLK_PACKAGESENTRY._serialized_options = b'8\001'
  _SYLK_SERVICESENTRY._options = None
  _SYLK_SERVICESENTRY._serialized_options = b'8\001'
  _SYLK._serialized_start=136
  _SYLK._serialized_end=611
  _SYLK_PACKAGESENTRY._serialized_start=451
  _SYLK_PACKAGESENTRY._serialized_end=528
  _SYLK_SERVICESENTRY._serialized_start=530
  _SYLK_SERVICESENTRY._serialized_end=611
# @@protoc_insertion_point(module_scope)
