# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SylkCommons.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper

from typing import overload, Iterator, List, Dict
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SylkCommons.proto\x12\x13sylk.SylkCommons.v1\x1a\x1cgoogle/protobuf/struct.proto\"=\n\x11SylkMethodContext\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\"f\n\x0fSylkFileContext\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x37\n\x07methods\x18\x02 \x03(\x0b\x32&.sylk.SylkCommons.v1.SylkMethodContext\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x0c\"B\n\x0bSylkContext\x12\x33\n\x05\x66iles\x18\x01 \x03(\x0b\x32$.sylk.SylkCommons.v1.SylkFileContext*\x8a\x01\n\x0eSylkExtensions\x12\x1a\n\x16UNKNOWN_SYLKEXTENSIONS\x10\x00\x12\x0f\n\x0b\x46ileOptions\x10\x01\x12\x12\n\x0eMessageOptions\x10\x02\x12\x10\n\x0c\x46ieldOptions\x10\x03\x12\x12\n\x0eServiceOptions\x10\x04\x12\x11\n\rMethodOptions\x10\x05\x42\x32Z0github.com/sylk/core/services/protos/SylkCommonsb\x06proto3')

_SYLKEXTENSIONS = DESCRIPTOR.enum_types_by_name['SylkExtensions']
SylkExtensions = enum_type_wrapper.EnumTypeWrapper(_SYLKEXTENSIONS)
UNKNOWN_SYLKEXTENSIONS = 0
FileOptions = 1
MessageOptions = 2
FieldOptions = 3
ServiceOptions = 4
MethodOptions = 5


_SYLKMETHODCONTEXT = DESCRIPTOR.message_types_by_name['SylkMethodContext']
_SYLKFILECONTEXT = DESCRIPTOR.message_types_by_name['SylkFileContext']
_SYLKCONTEXT = DESCRIPTOR.message_types_by_name['SylkContext']

@overload
class SylkMethodContext(_message.Message):
	"""webezyio generated message [sylk.SylkCommons.v1.SylkMethodContext]
	A class respresent a SylkMethodContext type
	
	"""
	name = str # type: str
	code = str # type: str
	type = str # type: str

	def __init__(self, name=str, code=str, type=str):
		"""
		Attributes:
		----------
		name : str
			
		code : str
			
		type : str
			
		"""
		pass
SylkMethodContext = _reflection.GeneratedProtocolMessageType('SylkMethodContext', (_message.Message,), {
  'DESCRIPTOR' : _SYLKMETHODCONTEXT,
  '__module__' : 'SylkCommons_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkCommons.v1.SylkMethodContext)
  })
_sym_db.RegisterMessage(SylkMethodContext)


@overload
class SylkFileContext(_message.Message):
	"""webezyio generated message [sylk.SylkCommons.v1.SylkFileContext]
	A class respresent a SylkFileContext type
	
	"""
	file = str # type: str
	methods = List[SylkMethodContext] # type: List[SylkMethodContext]
	code = None # type: None

	def __init__(self, file=str, methods=List[SylkMethodContext], code=None):
		"""
		Attributes:
		----------
		file : str
			
		methods : List[SylkMethodContext]
			
		code : None
			
		"""
		pass
SylkFileContext = _reflection.GeneratedProtocolMessageType('SylkFileContext', (_message.Message,), {
  'DESCRIPTOR' : _SYLKFILECONTEXT,
  '__module__' : 'SylkCommons_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkCommons.v1.SylkFileContext)
  })
_sym_db.RegisterMessage(SylkFileContext)


@overload
class SylkContext(_message.Message):
	"""webezyio generated message [sylk.SylkCommons.v1.SylkContext]
	A class respresent a SylkContext type
	
	"""
	files = List[SylkFileContext] # type: List[SylkFileContext]

	def __init__(self, files=List[SylkFileContext]):
		"""
		Attributes:
		----------
		files : List[SylkFileContext]
			
		"""
		pass
SylkContext = _reflection.GeneratedProtocolMessageType('SylkContext', (_message.Message,), {
  'DESCRIPTOR' : _SYLKCONTEXT,
  '__module__' : 'SylkCommons_pb2'
  # @@protoc_insertion_point(class_scope:sylk.SylkCommons.v1.SylkContext)
  })
_sym_db.RegisterMessage(SylkContext)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/sylk/core/services/protos/SylkCommons'
  _SYLKEXTENSIONS._serialized_start=308
  _SYLKEXTENSIONS._serialized_end=446
  _SYLKMETHODCONTEXT._serialized_start=72
  _SYLKMETHODCONTEXT._serialized_end=133
  _SYLKFILECONTEXT._serialized_start=135
  _SYLKFILECONTEXT._serialized_end=237
  _SYLKCONTEXT._serialized_start=239
  _SYLKCONTEXT._serialized_end=305
# @@protoc_insertion_point(module_scope)
