# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SamplePackage_pb2 as SamplePackage__pb2


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleUnary = channel.unary_unary(
                '/SampleService/SampleUnary',
                request_serializer=SamplePackage__pb2.SampleMessage.SerializeToString,
                response_deserializer=SamplePackage__pb2.SampleMessage.FromString,
                )


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SampleUnary(self, request, context):
        """[webezyio] - None
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleUnary,
                    request_deserializer=SamplePackage__pb2.SampleMessage.FromString,
                    response_serializer=SamplePackage__pb2.SampleMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SampleUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SampleService/SampleUnary',
            SamplePackage__pb2.SampleMessage.SerializeToString,
            SamplePackage__pb2.SampleMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
