# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SampleService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SamplePackage_pb2 as SamplePackage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SampleService.proto\x1a\x13SamplePackage.proto2n\n\rSampleService\x12]\n\x0bSampleUnary\x12&.domain.SamplePackage.v1.SampleMessage\x1a&.domain.SamplePackage.v1.SampleMessageb\x06proto3')



_SAMPLESERVICE = DESCRIPTOR.services_by_name['SampleService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLESERVICE._serialized_start=44
  _SAMPLESERVICE._serialized_end=154
# @@protoc_insertion_point(module_scope)
