# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OtherPackage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12OtherPackage.proto\x12\x16\x64omain.OtherPackage.v1\"\x1d\n\x08OtherMsg\x12\x11\n\ttestother\x18\x01 \x03(\tb\x06proto3')



_OTHERMSG = DESCRIPTOR.message_types_by_name['OtherMsg']
OtherMsg = _reflection.GeneratedProtocolMessageType('OtherMsg', (_message.Message,), {
  'DESCRIPTOR' : _OTHERMSG,
  '__module__' : 'OtherPackage_pb2'
  # @@protoc_insertion_point(class_scope:domain.OtherPackage.v1.OtherMsg)
  })
_sym_db.RegisterMessage(OtherMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OTHERMSG._serialized_start=46
  _OTHERMSG._serialized_end=75
# @@protoc_insertion_point(module_scope)
