# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SamplePackage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import OtherPackage_pb2 as OtherPackage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SamplePackage.proto\x12\x17\x64omain.SamplePackage.v1\x1a\x12OtherPackage.proto\"z\n\tSampleMsg\x12\x0c\n\x04test\x18\x01 \x01(\x08\x12\x11\n\ttestother\x18\x02 \x01(\t\x12\x16\n\x0etestotherfield\x18\x03 \x01(\x05\x12\x34\n\ntestparent\x18\x04 \x01(\x0b\x32 .domain.OtherPackage.v1.OtherMsg\"\x1d\n\x08OtherMsg\x12\x11\n\ttestother\x18\x01 \x03(\tb\x06proto3')



_SAMPLEMSG = DESCRIPTOR.message_types_by_name['SampleMsg']
_OTHERMSG = DESCRIPTOR.message_types_by_name['OtherMsg']
SampleMsg = _reflection.GeneratedProtocolMessageType('SampleMsg', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLEMSG,
  '__module__' : 'SamplePackage_pb2'
  # @@protoc_insertion_point(class_scope:domain.SamplePackage.v1.SampleMsg)
  })
_sym_db.RegisterMessage(SampleMsg)

OtherMsg = _reflection.GeneratedProtocolMessageType('OtherMsg', (_message.Message,), {
  'DESCRIPTOR' : _OTHERMSG,
  '__module__' : 'SamplePackage_pb2'
  # @@protoc_insertion_point(class_scope:domain.SamplePackage.v1.OtherMsg)
  })
_sym_db.RegisterMessage(OtherMsg)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAMPLEMSG._serialized_start=68
  _SAMPLEMSG._serialized_end=190
  _OTHERMSG._serialized_start=192
  _OTHERMSG._serialized_end=221
# @@protoc_insertion_point(module_scope)
