# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import OtherPackage_pb2 as OtherPackage__pb2
from . import SamplePackage_pb2 as SamplePackage__pb2


class SampleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SampleRPC = channel.unary_unary(
                '/SampleService/SampleRPC',
                request_serializer=SamplePackage__pb2.SampleMsg.SerializeToString,
                response_deserializer=OtherPackage__pb2.OtherMsg.FromString,
                )


class SampleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SampleRPC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SampleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SampleRPC': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleRPC,
                    request_deserializer=SamplePackage__pb2.SampleMsg.FromString,
                    response_serializer=OtherPackage__pb2.OtherMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SampleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SampleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SampleRPC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SampleService/SampleRPC',
            SamplePackage__pb2.SampleMsg.SerializeToString,
            OtherPackage__pb2.OtherMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
