# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import WebezyAnalytics_pb2 as WebezyAnalytics__pb2
from . import WebezyCore_pb2 as WebezyCore__pb2


class AnalyticsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishCLIEvent = channel.unary_unary(
                '/Analytics/PublishCLIEvent',
                request_serializer=WebezyAnalytics__pb2.CLIEvent.SerializeToString,
                response_deserializer=WebezyCore__pb2.OkResponse.FromString,
                )


class AnalyticsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishCLIEvent(self, request, context):
        """[webezyio] - This is an analytic event from CLI
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishCLIEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishCLIEvent,
                    request_deserializer=WebezyAnalytics__pb2.CLIEvent.FromString,
                    response_serializer=WebezyCore__pb2.OkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Analytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Analytics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishCLIEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Analytics/PublishCLIEvent',
            WebezyAnalytics__pb2.CLIEvent.SerializeToString,
            WebezyCore__pb2.OkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
