# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Analytics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import WebezyAnalytics_pb2 as WebezyAnalytics__pb2
from . import WebezyCore_pb2 as WebezyCore__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41nalytics.proto\x1a\x15WebezyAnalytics.proto\x1a\x10WebezyCore.proto2e\n\tAnalytics\x12X\n\x0fPublishCLIEvent\x12#.webezy.WebezyAnalytics.v1.CLIEvent\x1a .webezy.WebezyCore.v1.OkResponseb\x06proto3')



_ANALYTICS = DESCRIPTOR.services_by_name['Analytics']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANALYTICS._serialized_start=60
  _ANALYTICS._serialized_end=161
# @@protoc_insertion_point(module_scope)
