# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebezyCore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor

from typing import overload, Iterator, List
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10WebezyCore.proto\x12\x14webezy.WebezyCore.v1\"-\n\nOkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\tb\x06proto3')



_OKRESPONSE = DESCRIPTOR.message_types_by_name['OkResponse']

@overload
class OkResponse:
	"""webezyio generated message [webezy.WebezyCore.v1.OkResponse]
	A class respresent a OkResponse type
	"""
	status = str # type: str
	context = str # type: str

	def __init__(self, status=str, context=str):
		pass
OkResponse = _reflection.GeneratedProtocolMessageType('OkResponse', (_message.Message,), {
  'DESCRIPTOR' : _OKRESPONSE,
  '__module__' : 'WebezyCore_pb2'
  # @@protoc_insertion_point(class_scope:webezy.WebezyCore.v1.OkResponse)
  })
_sym_db.RegisterMessage(OkResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OKRESPONSE._serialized_start=42
  _OKRESPONSE._serialized_end=87
# @@protoc_insertion_point(module_scope)
